export default {
  self: 'xroom',
  on: '(+)',
  off: '(-)',
  title: 'Bruuchsch grad ä Videokonferenz?',
  buttons: {
    ok: 'OK',
    yes: 'Ja',
    no: 'Nei',
    cancel: 'Abbräche',
    retry: 'Nomal probiere',
    chooseWindow: 'Fänschter uuswähle',
    wholeScreen: 'Ganzä Bildschirm',
    install: 'Dezuefüege',
    uninstall: 'Entfärne',
    send: 'Sände',
    close: 'Schlüsse',
    hide: 'Verbergä',
    knock: 'Aachlopfe',
    allowIn: 'Zuetritt erlaube',
    deny: 'Ablehne',
    enterAnyway: 'Trotzdem iiträtte',
    details: 'Details',
  },
  mbox: {
    notSupported: 'Anschiinend understützt din Browser XROOM nöd oder WebRTC isch deaktiviert. 😢',
    success: 'Operation glunge',
    failure: 'Operation nöd glunge',
    enterRoomName: 'Bitte träg en Ruumname ii',
    isCamOn: 'Isch d´Kamera iigschaltet?',
    isCamOnText: 'Bitte lueg, dass nöd us Verseh d´Kamera oder s´Mikrofon für die Siitä blockiert isch, und klick dänn uf "Nomal probiere".',
    isMicOn: 'Isch s´Mikrofon iigschaltet?',
    isMicOnText: 'Demit redä chasch, musch zerscht s´Mikrofon iischalte. Bitte gib s´Mikrofon für die Siite frei und klick dänn uf "Nomal probiere".',
    iWillOnlyWatch: 'Ich wett nur zueluege',
    iWillOnlyListen: 'Ich wett nur zuelose',
    screenSharingText: 'Bildschirm teile isch nöd freigäh. Bitte lueg, dass es nöd blockiert isch für die Siite.<br><br> Usserdem wird die Funktion nur vo modernä Browser understützt, wie zum Biispiel Chrome oder Firefox.',
    cannotFile: 'Will mir übermittleti Dateie nöd emal berühred, chömmer sie nöd uusliefere, wänn gliichziitig no Lüt in Ruum iiträted. Dateie chönd erscht übermittled wärde, wänn alli Teilnehmer im Ruum ine sind.',
    cannotMessage: 'Will mir übermittleti Nachrichte nöd emal berühred, chömmer sie nöd uusliefere, wänn gliichziitig no Lüt in Ruum iiträted. Nachrichte chönd erscht übermittled wärde, wänn alli Teilnehmer im Ruum ine sind.',
    roomLockedText: 'Dä Ruum isch abgschlosse',
    oops: 'Sorry',
    kickedOutText: 'Du bisch usegschmisse worde',
    areYouSure: 'Bisch sicher?',
    restartRequiredText: 'Die Iistellig würkt sich uf zuvieli Funktionä uus, drum musch än Reload machä. Nur kei Uufregig, das gaht schnäll!',
    onlySafariOnIOS: 'Uf iOS wird nur Safari understützt. "Merci", Apple!',
    cannotLoadPlugin: 'Das Plugin "%s" understützt diin Browser nöd',
    confirmFileSend: 'Wettsch das abschickä?',
    whatIsYourName: 'Bitte tue din Name iitöggele',
    setVideoVolume: 'Da chasch d´Luutstärchi für das Video feschtlegä',
    roomLockedTryKnockText: 'Dä Ruum isch grad jetzt abgschlossä. Du chasch frööge, ob inechoo chasch, indem du "aachlopfe" tuesch.',
    knockingFailedText: 'Aachlopfe nöd glungä',
    doYouWantToKick: 'Wöttsch dä Teilnehmer useschmeisse?',
    deviceChanged: 'Du häsch es neus Empfangsgrät aagschlosse/abghänkt. Wänns nöd funktioniert, chasch es manuell i dä Iistellige uuswähle.',
    allowCameraPlz: 'Wänn du OK druckt häsch, lah bitte zue <b>dass</b> xroom dini Kamera bruuche därf.<br><br>Nur kei Uufregig! Du chasch si mit em Menu une wieder abschalte, bevor du in Ruum inegahsch, wenn du wottsch unsichtbar bliibe.',
    tooOldBrowser: 'Diin Browser isch z´alt oder er isch vo Microsoft. Es cha sii, dass e paar Funktionen nöd richtig tüend.',
    pluginsLoadFailed: 'Plugins händ nöd chönne glade wärde',
    protoExpired: 'Z´alti Client Version. Bitte druck uf Ctrl&nbsp;+&nbsp;Shift&nbsp;+&nbsp;F5 zum neu startä. Wänn dann die Nachricht nomal chunnt, tusch bitte dä Browser Cache manuell lääre.',
    peerError: 'Irgendöppis isch schief gange bim Dateuustuusch mit dine Peers. Am beschtä tuesch d´Siite neu lade.',
    enterpriseOnly: 'Die Funktion staht nur Firmenä zur Verfüegig.',
    pluginSuggested: 'Dä Teilnehmer %s schlaht vor, dass du s´Plugin %s inschtalliere söttsch. Wettsch das mache?',
    hostRoleRequired: 'Für diä Aktion musch du d´Rolle vomenä Host haa.',
    alreadyHosted: 'Dä Ruum da wird bereits ghostet. Bitte tue dä Ruum nöd vo zwei Browser-Tabs uus beträte. 😉',
    roomLockedPassword: 'Dä Ruum isch grad jetzt passwort-gsichered. Du chasch s´Passwort unä iitöggele, wänn du s´kennsch.',
    roomDestroyed: 'Dä Ruum isch zerstört wordä. Du wirsch zur Startsiite umgleitet.',
    roomBooked: 'Dä Ruum isch buecht worde und cha nöd us dä Schnittstell erstellt wärde, bis die Buechig abglaufe isch.',
    nameRequired: 'Dä Host vom Ruum bittet drum, dass du zerscht diin Namä inetöggelisch.',
  },
  notify: {
    slowPlugins: 'Die Plugins bruuched zvill Ziit zum Lade. Du chönntisch aber die schwärschte Plugins entfärne.',
  },
  home: {
    nisdos: 'Mir setzed kei Cookies ii',
    title: 'Diin persönlichä Konferenzruum',
    btnGo: 'Los!',
    knowMore: 'Über xroom',
    nameRoom: 'Namä für dä Ruum iitöggele:',
    placeholder: 'Da tippe',
    rejoinRoom: 'oder da nomal inegaa',
  },
  wl: {
    poweredBy: 'Unterstützt vo ',
  },
  modes: {
    1: 'Konfärenz',
    2: 'Webinar',
  },
  pre: {
    selectMode: 'Bitte tue s´Ruumformat uuswähle',
    checkIt: 'Check no schnäll diis Mikrofon und diini Friise...',
    btnGo: 'Inegaa',
    knockDenied: 'Dis Aachlopfe isch abglehnt worde. Du chasch dä Ruum nöd beträtte. :(',
    knockRequested: 'Warte uf Erlaubnis zum Inechoo. D´Lüüt im Ruum chönd dich dur es Fänschter gseeh. 👀',
    noAudio: '⚠️ Käs Mikrofon-Signal isch sichtbar',
    roomIsBusyWebinar: '<span>Äs Webinar / en Stream lauft grad</span> <span>(%s×🙂 / %s×🤖)</span>',
    roomIsBusyConference: '<span>Ä Konfärenz lauft grad</span> <span>(%s×🙂 / %s×🤖)</span>',
    sizeLimitReached: 'Dä Ruum hät e Grössebeschränkig, und s´Limit isch erreicht',
    roomBooked: 'There is going to be an event in this room at <b>%s</b>, but it has not started yet.',
  },
  videoMenu: {
    hint: 'Menu umschaltä',
    expand: 'Erwiitere',
    fullscreen: 'Vollbildschirm',
    volume: 'Luutstärchi ±',
    restore: 'Wiederherstellä',
    kick: 'Useschmeisse',
    mute: 'Stummschaltä',
  },
  controls: {
    ss: 'Bildschirm teilä %s',
    cam: 'Kamera %s',
    mic: 'Mikrofon %s',
    chat: 'Chat %s',
    exit: 'Usegaah',
    destroy: 'Zerstörä',
    xroom: 'Unterstützt vo xroom',
    settings: 'Iistellige',
    plugins: 'Plugins',
    media: 'Mediä',
    more: 'Meeh',
    letMeSpeak: 'Ich wott redä',
  },
  reactions: {
    letMeSpeak: 'Ich wott redä!',
  },
  waiting: {
    invite: 'Lad dini Kollegä ii',
    beforeCopy: 'Mit emene Klick kopierä',
    afterCopy: 'Kopiert. Jetzt teilä!',
    webinar: 'Das Webinar hat no nöd aagfangä',
  },
  video: {
    you: 'Du (klickä, zum dir sälber en Name z´gäh)',
    someone: 'Öpper',
    knocking: 'chlopft aa...',
    poorNet: 'schwachi Verbindig',
  },
  chat: {
    fileSending: 'Datei wird gsändet: ',
    fileReceived: 'Datei isch aachoo: ',
    inputPlaceholder: 'Schriib ä Nachricht und druck sändä ...',
    me: 'mich',
    dropMe: 'Lah mi us!',
  },
  webinar: {
    peersCount: '%s Lüüt lueged zue',
  },
  settings: {
    experimental: '*) experimentell, schafft no nöd stabil',
    showCameraWithScreen: 'Kamera sichtbar laah, während dä Bildschirm teilt wird *',
    audioQ: 'Audio quality',
    videoQ: 'Video quality',
    screenQ: 'Screen sharing quality',
    bandwidthQ: 'Bandwidth profile',
    autoGetIn: 'Chat ohni Vorschau startä',
    soundEffects: 'Toneffekt',
    noisyBackground: 'Ich bin in erä lärmigä Umgebig',
    rtcDebug: 'RTC debuggä',
    audioDevices: 'Audio Quelle',
    videoDevices: 'Video Quelle',
    language: 'Schprach',
    theme: 'Farb-Theme',
    server: 'Server',
    keepControls: 'D´Schalter sichtbar bhalte',
  },
  plugins: {
    by: 'vo',
    size: 'Grössi: %s kB',
    searchPlaceholder: 'suechä...',
    source: 'Quellcode: ',
    apiDocs: 'API Dokumänte',
    vendor: 'Verchäufer:',
    add: {
      title: 'Neus Plugin hinzuefüegä',
      descr: '⚙️ Bisch draa, es neus Plugin z´entwicklä? Chasch es da dezuefüege zum Teschtä. Es wird nienet abgspeichered, usser i diim Browser.',
      name: 'Wie heisst das Plugin?',
      rootUrl: 'Wo isch d root vom Plugin?',
      loaded: 'Super! Es wird glade!',
      loadFailed: 'Ladä vom Plugin nöd glungä',
    }
  },
  tips: {
    prefix: 'Tagestipp: ',
    lines: [
      'Schaltisch hüüfig stumm und wieder luut? Es git en Hot-Key "m" dadefür.',
      'Du chasch es Remote Video doppelklickä, zum s im Vollbildmodus aazeige.',
      'Wettsch diin Ruum abschlüsse? Eifach s´Room Locking Plugins us dä Plugins une dezuefüege.',
      'Nutzisch Slack und wettsch Ziit sparä? Probier üsen <a href="//xroom.app/en/library/slack-bot" target="_blank">Slack bot</a> uus.',
      'Vermissisch Video-Konfärenze in Telegram? Üsen <a href="//xroom.app/en/library/telegram-bot" target="_blank">Telegram bot</a> staht dir zur Verfüegig.',
      'Wettsch es kopierts Bild us dä Zwüscheablag teilä? Ctrl+V im Chat, dä Rescht mached miir.',
      'Klick da uf diin Namä, zum en lokal für diich und au für dini Peers z´änderä.',
      'Häsch scho immer welle din Bildschirm mit es paar Klicks wellä uufnääh? Probier üses Screen Recording Plugin uus.',
      'Wettsch während änerä Videokonfärenz öppis für alli sichtbar zeichnä — probier doch emal s´Sketching Plugin. Vergiss nöd, debii dä Bildschirm z´teilä.',
      'Klick uf diin Name oder "Du" zum dich für alli umztaufä.',
      'Klick uf d´Näme vo dinä Peers, zum ihri Luutstärchi iizstellä.',
    ]
  }
}
