export default {
  self: 'xroom',
  on: 'ανοιχτή',
  off: 'κλειστή',
  title: 'Χρειάζεσαι ένα δωμάτιο συνεδριάσεων?',
  buttons: {
    ok: 'ΟΚ',
    yes: 'Ναι',
    no: 'Όχι',
    cancel: 'Άκυρο',
    retry: 'Προσπάθησε ξανά',
    chooseWindow: 'Διάλεξε ένα παράθυρο',
    wholeScreen: 'Ολόκληρη οθόνη',
    install: 'Πρόσθεσε',
    uninstall: 'Αφαίρεσε',
    send: 'Στείλε',
    close: 'Κλείσε',
    hide: 'Κρύψε',
    knock: 'Τοκ τοκ',
    allowIn: 'Αποδοχή',
    deny: 'Απόρριψη',
    enterAnyway: 'Enter anyway',
    enterHost: 'Enter as a host',
    details: 'Details',
  },
  mbox: {
    notSupported: 'Φαίνεται ότι αυτό το πρόγραμμα περιήγησης δεν υποστηρίζει το XROOM ή το WebRTC είναι απενεργοποιημένο. 😢',
    success: 'Η λειτουργία ολοκληρώθηκε επιτυχώς',
    failure: 'Η λειτουργία απέτυχε',
    enterRoomName: 'Εισάγετε όνομα δωματίου παρακαλώ',
    isCamOn: 'Είναι η κάμερα σε λειτουργία?',
    isCamOnText: 'Παρακαλώ ελέγξτε ότι δεν έχετε παρεμποδίσει την κάμερα/το μικρόφωνο σε αυτόν τον ιστότοπο και πιέστε "Επανάληψη".',
    isMicOn: 'Είναι το μικρόφωνο ενεργοποιημένο?',
    isMicOnText: 'Εάν σκοπεύετε να μιλήσετε, χρειαζόμαστε την άδεια να χρησιμοποιήσουμε το μικρόφωνό σας. Επιτρέψτε το σε αυτόν τον ιστότοπο και πιέστε "Επανάληψη".',
    iWillOnlyWatch: 'Θα παρακολουθώ μόνο',
    iWillOnlyListen: 'Θα ακούω μόνο',
    screenSharingText: 'Η κοινή χρήση οθόνης δεν επιτρέπεται. Βεβαιωθείτε ότι δεν έχει αποκλειστεί σε αυτή τη σελίδα.<br><br>Επίσης αυτή η λειτουργία υποστηρίζεται μόνο από σύγχρονα προγράμματα περιήγησης όπως το Chrome ή ο Firefox.',
    cannotFile: 'Δεδομένου ότι δεν αγγίζουμε καν τα αρχεία σας, δεν μπορούμε να τα παραδώσουμε αφού κάποιος συνδεθεί. Πρέπει να το κάνετε online.',
    cannotMessage: 'Δεδομένου ότι δεν αγγίζουμε καν τα μηνύματά σας, δεν μπορούμε να τα παραδώσουμε αφού κάποιος συνδεθεί. Πρέπει να το κάνετε online.',
    roomLockedText: 'Αυτό το δωμάτιο είναι κλειδωμένο',
    oops: 'Συγγνώμη',
    kickedOutText: 'Σας πέταξαν εκτός δωματίου',
    areYouSure: 'Είστε σίγουρος/η?',
    doYouWantToLeave: 'Θέλετε πραγματικά να φύγετε από το δωμάτιο?',
    doYouWantToLeaveAsHost: 'Θέλετε πραγματικά να φύγετε από το δωμάτιο?',
    restartRequiredText: 'Αυτή η ρύθμιση επηρεάζει πολλά πράγματα, μια επαναφόρτωση απαιτείτε. Αυτό θα γίνει γρήγορα, μην ανησυχείτε!',
    onlySafariOnIOS: 'Στα iOS μόνο ο περιηγητής Safari υποστηρίζεται. "Ευχαριστούμε", Apple!',
    cannotLoadPlugin: 'Το πρόσθετο "%s" δεν υποστηρίζει τον περιηγητή',
    confirmFileSend: 'Θέλετε να στείλετε αυτό?',
    whatIsYourName: 'Δώστε καινούριο όνομα',
    setVideoVolume: 'Καθορίστε την ένταση για αυτό το βίντεο',
    roomLockedTryKnockText: 'Το δωμάτιο είναι προσωρινά κλειδωμένο. Μπορείτε να ζητήσετε την άδεια να μπείτε με το να "χτυπήσετε" την πόρτα.',
    knockingFailedText: 'Η προσπάθεια χτυπήματος απέτυχε',
    doYouWantToKick: 'Θέλετε να διώξετε αυτόν τον χρήστη?',
    deviceChanged: '΄Έχετε προσθέσει/αφαιρέσει μια νέα συσκευή εισόδου. Εάν δεν λειτουργεί διαλέξτε την χειροκίνητα από τις Ρυθμίσεις.',
    allowCameraPlz: 'Αφού πιέσετε OK παρακαλώ <b>επιτρέψτε</b> στο xroom να χρησιμοποιήσει την κάμερα.<br><br>Μην ανησυχείτε! Θα μπορέσετε να την απενεργοποιήσετε ξανά προτού μπείτε στο δωμάτιο από το μενού στο κάτω μέρος της οθόνης εαν θέλετε να είστε αόρατος/η.',
    tooOldBrowser: 'Ο περιηγητής σας είναι πολύ παλιός ή παράγεται από την Microsoft. Πολλά πρόσθετα μπορεί να λείπουν.',
    pluginsLoadFailed: 'Αποτυχία φόρτωσης plugins',
    protoExpired: 'Too old client version. Please press Ctrl&nbsp;+&nbsp;Shift&nbsp;+&nbsp;F5 to reload. If you then see this message again please clear browser cache manually.',
    peerError: 'Something went wrong when exchanging data with your peers. We suggest reloading the page.',
    pluginSuggested: 'User %s suggested you to install plugin %s. Do you wish to do it?',
    hostRoleRequired: 'Host role is required for this action.',
    alreadyHosted: 'Room is already hosted. Do not enter the same room from 2 browser tabs. 😉',
    roomLockedPassword: 'Room is currently locked with a password. Enter it below if you know it.',
    roomDestroyed: 'Room has been destroyed. You will be redirected to the starting page.',
    roomBooked: 'Room has been booked and cannot be created through the interface until booking expires.',
    nameRequired: 'Room host requires you to set your name first.',
    pipNotSupported: 'Your browser supports "picture-in-picture" mode but it is disabled somewhere in its settings.',
    copyFailed: 'Copying failed. This may be a result of your device restrictions.',
    noCryptoWarning: 'This browser does not support cryptography. It is not safe to continue.',
    bigFileDecryptWarn: 'Downloading has started. It may take a few seconds to decrypt the file.',
    roomMigrated: 'This room has been taken over by a booked meeting. Your call has been moved to another place and you will now be redirected there.',
  },
  notify: {
    slowPlugins: 'Plugins take too much time to load. Consider removing the heaviest.',
  },
  home: {
    nisdos: 'Δεν χρησιμοποιούμε cookies',
    title: 'Το προσωπικό σας δωμάτιο συνεδριάσεων',
    btnGo: 'Ξεκίνα!',
    knowMore: 'Σχετικά με το xroom',
    nameRoom: 'ονομάστε το δωμάτιό σας:',
    placeholder: 'πληκτρολογήστε εδώ',
    rejoinRoom: 'ή επανασυνδεθείτε',
  },
  wl: {
    poweredBy: 'Powered by ',
  },
  modes: {
    1: 'Conference',
    2: 'Webinar',
  },
  pre: {
    selectMode: 'Choose room type',
    checkIt: 'Ελέγξτε το μικρόφωνο και το κούρεμά σας',
    btnGo: 'Εισέλθετε',
    knockDenied: 'Η αίτηση χτυπήματός σας έχει απορριφθεί. Δεν μπορείτε να εισέλθετε στο δωμάτιο. :(',
    knockRequested: 'Αναμονή για άδεια. Είστε ορατός/ή σε άλλους από το ματάκι της πόρτας. 👀',
    noAudio: '⚠️ Δεν εντοπίστηκε σήμα μικροφώνου',
    roomIsBusyWebinar: 'A webinar/stream is already running (%s × 🙂)',
    roomIsBusyConference: 'A conference is now running (%s × 🙂)',
    sizeLimitReached: 'This room was limited by size and the limit is reached',
    roomBooked: 'There is going to be an event in this room at <b>%s</b>, but it has not started yet.',
  },
  videoMenu: {
    hint: 'Εναλλάξτε το μενού',
    expand: 'Επέκταση',
    pip: 'Keep on top',
    fullscreen: 'Πλήρης οθόνη',
    volume: 'Ένταση ±',
    restore: 'Επαναφορά',
    kick: 'Διώξτε',
  },
  controls: {
    ss: 'Διαμοιρασμός οθόνης %s',
    cam: 'Κάμερα %s',
    mic: 'Μικρόφωνο %s',
    chat: 'Ομιλία %s',
    exit: 'Έξοδος',
    xroom: 'Powered by xroom',
    settings: 'Ρυθμίσεις',
    plugins: 'Πρόσθετα',
    media: 'Media',
    more: 'Πιό',
    letMeSpeak: 'Let me speak',
    lock: 'Locking',
  },
  lockStatus: {
    locked: 'Room is locked',
    open: 'Room is open',
    protected: 'Room is password-protected',
    placeholder: 'room password',
  },
  reactions: {
    letMeSpeak: 'I want to speak!',
  },
  waiting: {
    invite: 'Προσκαλέστε τους συναδέλφους σας',
    beforeCopy: 'κάντε κλικ για αντιγραφή',
    afterCopy: 'αντιγράφηκε!',
    webinar: 'Το webinar δεν ξεκίνησε ακόμα',
  },
  video: {
    you: 'Εσείς',
    someone: 'Κάποιος',
    knocking: 'χτυπάει..',
    poorNet: 'φτωχή σύνδεση',
  },
  chat: {
    fileSending: 'Αποστολή αρχείου: ',
    fileReceived: 'Το αρχείο λήφθηκε: ',
    inputPlaceholder: 'πληκτρολογήστε ένα μήνυμα και πατήστε enter ...',
    me: 'εγώ',
    dropMe: 'Πέτα με!',
  },
  webinar: {
    peersCount: '%s άτομα βλέπουν',
  },
  settings: {
    experimental: '*) πειραματικό, λειτουργεί με αστάθεια',
    screenFace: 'Δείξτε την κάμερα κατά την διάρκεια της κοινής χρήσης οθόνης (BETA)',
    audioQ: 'Audio quality',
    videoQ: 'Video quality',
    screenQ: 'Screen sharing quality',
    bandwidthQ: 'Bandwidth profile',
    autoGetIn: 'Ξεκινήστε τις συζητήσεις χωρίς προεπισκόπηση',
    soundEffects: 'Ηχητικά εφέ',
    noisyBackground: 'Βρίσκομαι σε ένα θορυβώδες μέρος',
    rtcDebug: 'Εντοπισμός σφαλμάτων RTC',
    audioDevices: 'Πηγές ήχου',
    videoDevices: 'Πηγές βίντεο',
    language: 'Γλώσσα',
    theme: 'Χρώμα θέμα',
    server: 'Server',
    keepControls: 'Keep controls visible',
  },
  plugins: {
    by: 'απο',
    size: 'Μέγεθος: %s kB',
    searchPlaceholder: 'αναζήτηση...',
    source: 'Πηγαίος κώδικας:',
    apiDocs: 'API docs',
    vendor: 'Vendor:',
    add: {
      title: 'Προσθέστε νεο plugin',
      descr: '⚙️ Αναπτύσσετε ένα νέο plugin? Προσθέστε το εδώ για τεστ. Δεν σώζεται, η επαναφόρτιση της σελίδας την αφαιρεί από την μνήμη.',
      name: 'Ποιο είναι το όνομα του plugin?',
      rootUrl: 'Που είναι η πηγή του plugin?',
      loaded: 'Ναι! Φορτώθηκε!',
      loadFailed: 'Απέτυχε η φόρτωση του plugin',
    }
  },
}
