module.exports = {
  self: 'xroom',
  title: 'Tu espacio de trabajo seguro',
  goToDash: 'Ir al dashboard',
  netStatus: 'Conección',
  buttons: {
    ok: 'OK',
    cancel: 'Cancelar',
    yes: 'Si',
    no: 'No',
    chN: 'Opción %s',
    install: 'Agregar',
    uninstall: 'Eliminar',
    details: 'Ver detalles',
    close: 'Cerrar',
    next: 'Seguir',
    back: 'Regresar',
    retry: 'Rever',
    dismiss: 'Despedir',
    allow: 'Permitir',
    stop: 'Parar',
  },
  mbox: {
    protoExpired: 'Versión del cliente es muy antigua. Presione Ctrl&nbsp;+&nbsp;Shift&nbsp;+&nbsp;F5 para volver a reiniciar. Si luego vuelve a ver este mensaje, borre la memoria caché del navegador manualmente.',
    areYouSure: '¿Estas seguro?',
    noPermission: 'No se pueden adquirir permisos de su browser. Asegúrese de que no estén bloqueados.',
    mediaBlocked: 'El acceso a la cámara está bloqueado. Asegúrese de no utilizarlo en otro browser o programa.',
    mediaError: 'No pudimos identificar el problema, algo no funciono. Compruebe los permisos de su browser.',
    whatIsYourName: '¿Cual es su nombre?',
    noPeers: 'No se usan los servidores de xroom.app para enviar mensajes y no se pueden reenviar cuando nuevo invitados se conectan. Espere hasta que otros se hayan conectado al cuarto para enviar mensajes.',
    password: 'Crear contraseña',
    roomLocked: 'Esta habitación está cerrada. ¿Quieres tocar para entrar?',
    roomProtected: 'Este cuarto está protegido con una contraseña. Por favor ingreselo para entrar.',
    roomIsFull: 'El cuarto esta lleno. No puede entrar.',
    alreadyHosted: 'Ya estás en el cuarto. Probablemente estas probando con varias pestañas del browser abiertas a la misma vez. ¿Quieres continuar? Es posible que las funciones de host no funcionen aquí.',
    youAreKicked: 'Has sido removido de este cuarto.',
    setQFailed: 'No se pudo establecer la calidad solicitada. Es posible que su hardware o browser no lo soporta.',
    bookingEnded: 'Esta reservación ya termino. El cuarto está reservado para otro evento, por lo que ahora será dirigido a otra sala para finalizar su reunión.',
    bookingEndedHost: 'La reservación para esta cuarto terminará pronto. Ahora debe hacer una selección ya que hay otra reservación en el mismo cuarto. <br/> <br/> 1. Vaya a una nueva reunión. Lo dirigiremos al dashboard para ingresar a la reunión con una nueva clave de host. <br/> <br/> 2. Quédate en la reunión. Crearemos una nueva sala para que finalices esta llamada.',
    pluginsLoadFailed: 'Error al descargar plugins',
    roomDestroyed: 'El cuarto ha sido eliminado. Serás dirigido a la página de inicio.',
    encInfo: 'Encryption: end-to-end, ECDH+AES<br/>Hash: <code>%s</code>',
    encFailure: 'Encryption no es soportado',
    avaTooBig: 'El tamaño del archivo de avatar es demasiado grande. Por favor utilice imágenes simples de vector.',
    cannotLoadPlugin: 'Plugin "%s" no es compatible con su browser',
    confirmLeave: '¿Estás seguro que quiere dejar la llamada?',
    confirmDestroy: '¿Está seguro de que quiere terminar la llamada para todos los participantes?',
    feedbackDetected: 'Hemos detectado ruidos del micrófono y lo hemos silenciado automáticamente. Le sugerimos que use sus audífonos o que mantenga el micrófono apagado hasta que ingrese al cuarto.',
    guestKnock: 'El usuario <b>%s</b> quiere entrar. ¿Permitir la entrada? <br/> Puedes decidir más tarde en la pestaña de la sala de espera.',
    safariNotSupported: 'Esta función no esta soportada temporalmente en Safari.',
    takeOverSharing: 'Sharing your screen now will end the current screen sharing session.',
  },
  notify: {
    slowPlugins: 'Demasiados plugins pueden hacer que la pagina se descarga lentamente. Considere quitar los más grandes.',
    peerLost: 'Reconectando con %s...',
    roomLocked: 'Cuarto cerrada 🔒',
    roomUnlocked: 'Cuarto desbloqueado 🔓',
    roomPwdSet: 'Contraseña aplicada al cuarto 🔑',
    roomPwdReset: 'Contraseña removida del cuarto ',
    devicesChanged: 'Dispositivos cambiados',
    hostMutedAudio: 'El host apago su micrófono',
    hostMutedVideo: 'Host apagó su cámara',
    incomingFile: 'Archivo entrando...',
  },
  modes: {
    '1': 'Conferencia - todos pueden hablar',
    '2': 'Webinar: uno habla, otros escuchan',
  },
  placements: {
    '1': 'Grid view',
    '2': 'Mini-me',
    '3': 'Spotlight',
  },
  perm: {
    head: 'Permitir permisos del browser',
    video: 'Video',
    audio: 'Audio',
    notif: 'Notificaciones',
  },
  videoMenu: {
    hint: 'Menú',
    expand: 'Expandir',
    pip: 'Keep on top',
    fullscreen: 'Pantalla completa',
    fullscreenOff: 'Salir de pantalla completa',
    volume: 'Volumen',
    restore: 'Restaurar',
    kick: 'Remover participante',
    mute: 'Silenciar (solo para ti)',
    unmute: 'Activar sonido',
    pm: 'Chat privado',
    makeHost: 'Pase el rol de host',
  },
  controls: {
    sharing: 'Compartir',
    cam: 'Cámara',
    mic: 'Micrófono',
    chat: 'Chat',
    exit: 'Salir',
    destroy: 'Finalizar reunión',
    settings: 'Configuración',
    plugin: 'Plugins',
    dots: 'Menú',
    invite: 'Invitar',
    ss: 'Compartir pantalla',
    stopSharing: 'Dejar de compartir',
    board: 'Whiteboard',
    hand: 'Levantar la mano',
    lock: 'Cerradura',
    layouts: 'Colocación',
    emoji: 'Emojis',
    attach: 'Adjuntar un archivo',
    setLock: 'Bloquear el cuarto',
    resetLock: 'Desbloquear el cuarto',
    setPwd: 'Establecer una contraseña',
    rotate: 'Cámara trasera/frontal',
    more: 'Mas',
    users: 'Participantes',
  },
  reactions: {
    handRaised: 'Usuario %s quiere hablar 🎤',
  },
  video: {
    you: 'Usted (haga clic para nombrar)',
    sharing: 'Estás compartiendo tu pantalla',
  },
  settings: {
    tabs: {
      audio: 'Audio',
      video: 'Video',
      general: 'General',
      help: 'Ayuda',
      chat: 'Chat',
      peers: 'Participantes',
      lobby: 'Sala de espera',
    },
    audioQ: 'Frecuencia de muestreo máxima',
    videoQ: 'Calidad de video máxima',
    screenQ: 'Calidad máxima para compartir pantalla',
    bandwidthQ: 'Perfil de ancho de banda',
    soundEffects: 'Efectos de sonido',
    audioDevices: 'Fuentes de audio',
    videoDevices: 'Fuentes de video',
    language: 'Idioma',
    theme: 'Tema de color',
    requestAudio: 'Solicitar permiso de audio',
    requestVideo: 'Solicitar permiso de video',
    testOutput: 'Prueba su audio',
    flipFace: 'Refleja la vista de su cámara',
    requireName: 'Requerir nombre',
    debug: 'Modo de debug',
    noPreview: 'Empezar chat sin previsualización',
    menuPos: 'Colocación del menú',
    menuPosO: {
      '1': 'Arriba',
      '2': 'Abajo',
    },
  },
  home: {
    title: 'Tu sala de conferencias personal',
    btnGo: '¡Avanzar!',
    nameRoom: 'nombra su cuarto:',
    placeholder: 'escriba aquí',
    rejoinRoom: 'o volver a unirse en',
    poweredBy: 'Creado por <a href="https://xroom.app">xroom.app</a>',
    roomHint: 'Ingresar nombre del cuarto',
  },
  pre: {
    selectMode: 'Elija el tipo de reunión',
    selectedMode: 'Tipo de reunión',
    btnGo: 'Entrar',
    btnPreview: 'Previsualizar',
    avaPicker: 'Elija avatar (se muestra cuando su video está apagado)',
    sizeLimitReached: 'Esta habitación esta limitada en tamaño y se ha alcanzado el límite',
    roomBooked: 'Pronto habrá un evento en esta sala: <span>%s<span>. <br/> Espere hasta que comience la reunión.',
    roomInfo: 'Información del cuarto',
    phInfo: 'Ingrese la información del cuarto',
    pendingAdmission: 'Espere hasta que el host le deje entrar.',
  },
  inviter: {
    info: 'Comparta el link para invitar a otras personas al cuarto.',
    head: 'Link del cuarto:',
    btnCopy: 'Copiar link',
    btnShare: 'Compartir link',
    ntfCopied: '¡El link ha sido copiado!',
  },
  chat: {
    publicChat: 'Chat público',
    chatWith: 'Chat con %s',
    fileSending: 'Enviando archivo: ',
    fileReceived: 'Archivo recibido: ',
    phInput: 'Escribe un mensaje...',
    me: 'yo',
    dropMe: '¡Suéltame!',
    atTime: 'a las %s',
  },
  peers: {
    muteOnEntry: 'Silenciar los participantes al entrar',
    camsOff: 'Apagar todos los videos',
    micsOff: 'Silenciar a todos',
  },
  knockers: {
    phEmpty: 'Si alguien toca para entrar a su cuarto, aparecerán aquí, esperando por su aprobación.',
  },
  webinar: {
    peersCount: {
      one: '%s persona está mirando',
      many: '%s personas están mirando',
    },
  },
  plugins: {
    by: 'de',
    size: 'Tamaño: %s kB',
    phSearch: 'buscar...',
    source: 'Código fuente:',
    apiDocs: 'Docs API',
    vendor: 'Vendedor:',
    btnAdd: 'Agregar propio',
    add: {
      title: 'Agregar plugin nuevo',
      descr: '⚙️ ¿Desarrollando un plugin nuevo? Agrégalo aquí para probar. No se guarda, al reinciar la página se borra de la memoria.',
      name: '¿Nombre del plugin?',
      rootUrl: '¿Dónde está la fuente del plugin?',
      loaded: '¡Sí! ¡Se cargó!',
      loadFailed: 'Falló la carga del plugin',
    }
  },
  help: {
    sevenTips: 'Top 7 Issues/Fixes',
    connIssues: 'Connection issues',
    laggyMedia: 'Laggy audio/video',
    unlockMedia: 'Unblock camera/mic',
    faq: 'Go to FAQ',
    submitFeature: 'Request a feature',
  },
}
