module.exports = {
  self: 'xroom',
  title: 'Tu espacio de trabajo seguro',
  goToDash: 'Ir al dashboard',
  netStatus: 'Conección',
  buttons: {
    ok: 'OK',
    cancel: 'Cancelar',
    yes: 'Si',
    no: 'No',
    chN: 'Opción %s',
    install: 'Agregar',
    uninstall: 'Eliminar',
    details: 'Ver detalles',
    close: 'Cerrar',
    next: 'Seguir',
    back: 'Regresar',
    retry: 'Rever',
    dismiss: 'Despedir',
    allow: 'Permitir',
    stop: 'Parar',
    decideLater: 'Decide después',
    knock: 'Knock',
    leave: 'Leave',
  },
  mbox: {
    notSupported: 'Parece que este navegador no soporta xroom.app o WebRTC está deshabilitado. 😢',
    protoExpired: 'Versión del cliente es muy antigua. Presione Ctrl&nbsp;+&nbsp;Shift&nbsp;+&nbsp;F5 para volver a reiniciar. Si luego vuelve a ver este mensaje, borre la memoria caché del navegador manualmente.',
    areYouSure: '¿Estas seguro?',
    noPermission: 'No se pueden adquirir permisos de su browser. Asegúrese de que no estén bloqueados.',
    mediaBlocked: 'El acceso a la cámara está bloqueado. Asegúrese de no utilizarlo en otro browser o programa.',
    mediaError: 'You provided access to your hardware devices, but a local problem in your system prevented your device from being used. Please try another browser or another device.',
    whatIsYourName: '¿Cual es su nombre?',
    noPeersP2P: 'No se usan los servidores de xroom.app para enviar mensajes y no se pueden reenviar cuando nuevo invitados se conectan. Espere hasta que otros se hayan conectado al cuarto para enviar mensajes.',
    noPeers: 'No se pueden reenviar mensajes cuando nuevo invitados se conectan. Espere hasta que otros se hayan conectado al cuarto para enviar mensajes.',
    password: 'Crear contraseña',
    roomLocked: 'Esta habitación está cerrada. ¿Quieres tocar para entrar?',
    roomProtected: 'Este cuarto está protegido con una contraseña. Por favor ingreselo para entrar.',
    roomIsFull: 'El cuarto esta lleno. No puede entrar.',
    alreadyHosted: 'Ya estás en el cuarto. Probablemente estas probando con varias pestañas del browser abiertas a la misma vez. ¿Quieres continuar? Es posible que las funciones de host no funcionen aquí.',
    youAreKicked: 'Has sido removido de este cuarto.',
    setQFailed: 'No se pudo establecer la calidad solicitada. Es posible que su hardware o browser no lo soporta.',
    bookingEnded: 'Esta reservación ya termino. El cuarto está reservado para otro evento, por lo que ahora será dirigido a otra sala para finalizar su reunión.',
    bookingEndedHost: 'La reservación para esta cuarto terminará pronto. Ahora debe hacer una selección ya que hay otra reservación en el mismo cuarto. <br/> <br/> 1. Vaya a una nueva reunión. Lo dirigiremos al dashboard para ingresar a la reunión con una nueva clave de host. <br/> <br/> 2. Quédate en la reunión. Crearemos una nueva sala para que finalices esta llamada.',
    pluginsLoadFailed: 'Error al descargar plugins',
    roomDestroyed: 'El cuarto ha sido eliminado. Serás dirigido a la página de inicio.',
    encInfo: 'Encryption: end-to-end, ECDH+AES<br/>Hash: <code>%s</code>',
    encFailure: 'Encryption no es soportado',
    avaTooBig: 'El tamaño del archivo de avatar es demasiado grande. Por favor utilice imágenes simples de vector.',
    cannotLoadPlugin: 'Plugin "%s" no es compatible con su browser',
    confirmLeave: '¿Estás seguro que quiere dejar la llamada?',
    confirmDestroy: '¿Está seguro de que quiere terminar la llamada para todos los participantes?',
    feedbackDetected: 'Hemos detectado ruidos del micrófono y lo hemos silenciado automáticamente. Le sugerimos que use sus audífonos o que mantenga el micrófono apagado hasta que ingrese al cuarto.',
    guestKnock: 'El usuario <b>%s</b> quiere entrar. ¿Permitir la entrada? <br/> Puedes decidir más tarde en la pestaña de la sala de espera.',
    safariNotSupported: 'Esta función no esta soportada temporalmente en Safari.',
    p2pNotSupported: 'Esta función está desactivada en el modo peer-to-peer.',
    takeOverSharing: 'Si comparte su pantalla, terminara la sesión actual de la persona que esta compartiendo ahorita.',
    p2pInfo: 'El modo P2P desactiva el uso de nuestros servidores centralizados.<br/><u>La estabilidad de la sala dependerá entonces en su conección.</u><br/>Recomendado para reuniones privadas de 2 personas.',
    confirmKick: '¿Estás seguro de que deseas remover a %s del cuarto?',
    comingSoon: 'Esta función estará disponible muy pronto.',
    audioChanged: 'Se agregó un dispositivo de audio. ¿Quieres seleccionar cuál usar ahorita?',
    domainNotSetUp: 'This domain has not yet been set up. If you are its owner please do it in the dashboard. We will now forward you to our free service.',
    domainNotPaid: 'Your account has been temporarily deactivated due to not being current on payments. We will now forward you to our free service.',
    badLuck: 'Something went seriously wrong with the network. We will now try to reload your browser.',
    noEmbedding: 'Embedding protection is on. You may turn it off in the dashboard.',
  },
  notify: {
    slowPlugins: 'Demasiados plugins pueden hacer que la pagina se descarga lentamente. Considere quitar los más grandes.',
    peerLost: 'Reconectando con %s...',
    roomLocked: 'Cuarto cerrada 🔒',
    roomUnlocked: 'Cuarto desbloqueado 🔓',
    roomPwdSet: 'Contraseña aplicada al cuarto 🔑',
    roomPwdReset: 'Contraseña removida del cuarto ',
    devicesChanged: 'Dispositivos cambiados',
    hostMutedAudio: 'El host apago su micrófono',
    hostMutedVideo: 'Host apagó su cámara',
    incomingFile: 'Archivo entrando...',
  },
  hint: {
    p2p: '<u>xroom.app</u> utiliza servidores para garantizar transmisiones de alta calidad durante sus reuniones.<br/><br/>• Nunca tenemos acceso a sus comunicaciones en este modo.<br/><br/>• Todos los datos enviados a través de nuestros servidores están encriptados y bloqueados con claves a las que solo usted y sus invitados tienen acceso.<br/><br/><u>Si necesita la máxima seguridad,</u> puede deshabilitar nuestros servidores y, en su lugar, utilizar Modo punto a punto.<br/><br/>• En este modo, el video y el audio se envían directamente entre usted y sus invitados sin usar servidores xroom.app.<br/><br/>• Recomendamos usar par modo-a-pares cuando anticipa tener una reunión 1:1.',
  },
  modes: {
    '1': 'Conferencia - todos pueden hablar',
    '2': 'Webinar: uno habla, otros escuchan',
  },
  placements: {
    '1': 'Grid view',
    '2': 'Mini-me',
    '3': 'Spotlight',
  },
  perm: {
    head: 'Permitir permisos del browser',
    video: 'Video',
    audio: 'Audio',
    notif: 'Notificaciones',
  },
  videoMenu: {
    hint: 'Menú',
    expand: 'Expandir',
    pip: 'Keep on top',
    fullscreen: 'Pantalla completa',
    fullscreenOff: 'Salir de pantalla completa',
    volume: 'Volumen',
    restore: 'Restaurar',
    kick: 'Remover participante',
    mute: 'Silenciar (solo para ti)',
    unmute: 'Activar sonido',
    pm: 'Chat privado',
    makeHost: 'Pase el rol de host',
  },
  controls: {
    sharing: 'Compartir',
    cam: 'Cámara',
    mic: 'Micrófono',
    chat: 'Chat',
    exit: 'Salir',
    destroy: 'Finalizar reunión',
    settings: 'Configuración',
    plugin: 'Plugins',
    dots: 'Menú',
    invite: 'Invitar',
    ss: 'Compartir pantalla',
    stopSharing: 'Dejar de compartir',
    board: 'Whiteboard',
    hand: 'Levantar la mano',
    lock: 'Cerradura',
    layouts: 'Colocación',
    emoji: 'Emojis',
    attach: 'Adjuntar un archivo',
    setLock: 'Bloquear el cuarto',
    resetLock: 'Desbloquear el cuarto',
    setPwd: 'Establecer una contraseña',
    rotate: 'Cámara trasera/frontal',
    more: 'Mas',
    users: 'Participantes',
  },
  reactions: {
    handRaised: 'Usuario %s quiere hablar 🎤',
  },
  video: {
    you: 'Usted (haga clic para nombrar)',
    sharing: 'Estás compartiendo tu pantalla',
  },
  settings: {
    tabs: {
      audio: 'Audio',
      video: 'Video',
      general: 'General',
      help: 'Ayuda',
      chat: 'Chat',
      peers: 'Participantes',
      lobby: 'Sala de espera',
    },
    audioQ: 'Frecuencia de muestreo máxima',
    videoQ: 'Calidad de video máxima',
    screenQ: 'Calidad máxima para compartir pantalla',
    bandwidthQ: 'Perfil de ancho de banda',
    soundEffects: 'Efectos de sonido',
    audioDevices: 'Fuentes de audio',
    videoDevices: 'Fuentes de video',
    language: 'Idioma',
    theme: 'Tema de color',
    requestAudio: 'Solicitar permiso de audio',
    requestVideo: 'Solicitar permiso de video',
    testOutput: 'Prueba su audio',
    flipFace: 'Refleja la vista de su cámara',
    requireName: 'Requerir nombre',
    debug: 'Modo de debug',
    noPreview: 'Empezar chat sin previsualización',
    menuPos: 'Colocación del menú',
    menuPosO: {
      '1': 'Arriba',
      '2': 'Abajo',
    },
    name: 'Crear/ajustar su nombre',
    phName: 'su nombre',
  },
  home: {
    title: 'Tu sala de conferencias personal',
    btnGo: '¡Avanzar!',
    nameRoom: 'nombra su cuarto:',
    placeholder: 'escriba aquí',
    rejoinRoom: 'o volver a unirse en',
    poweredBy: 'Creado por <a href="https://xroom.app">xroom.app</a>',
    roomHint: 'Ingresar nombre del cuarto',
  },
  pre: {
    selectMode: 'Elija el tipo de reunión',
    selectedMode: 'Tipo de reunión',
    btnGo: 'Entrar',
    btnPreview: 'Previsualizar',
    avaPicker: 'Elija avatar (se muestra cuando su video está apagado)',
    sizeLimitReached: 'Esta habitación esta limitada en tamaño y se ha alcanzado el límite',
    roomBooked: 'Pronto habrá un evento en esta sala: <span>%s<span>. <br/> Espere hasta que comience la reunión.',
    roomInfo: 'Información del cuarto',
    phInfo: 'Ingrese la información del cuarto',
    pendingAdmission: 'Espere hasta que el host le deje entrar.',
    p2pMode: 'Modo Peer-to-peer',
    btnGoHome: 'Go to start page',
    btnAsHost: 'Enter as a host',
    roomLocked: 'This room is locked by the host.<br />Please knock to enter.',
    roomLockedInfo: 'Please enter your name.<br />Otherwise the host might not allow you into the meeting.',
  },
  inviter: {
    info: 'Comparta el link para invitar a otras personas al cuarto.',
    head: 'Link del cuarto:',
    btnCopy: 'Copiar link',
    btnShare: 'Compartir link',
    ntfCopied: '¡El link ha sido copiado!',
  },
  chat: {
    publicChat: 'Chat público',
    chatWith: 'Chat con %s',
    fileSending: 'Enviando archivo: ',
    fileReceived: 'Archivo recibido: ',
    phInput: 'Escribe un mensaje...',
    me: 'yo',
    dropMe: '¡Suéltame!',
    atTime: 'a las %s',
    recvProgress: 'recibe datos cifrados: %s%...',
  },
  peers: {
    muteOnEntry: 'Silenciar los participantes al entrar',
    camsOff: 'Apagar todos los videos',
    micsOff: 'Silenciar a todos',
  },
  knockers: {
    phEmpty: 'Si alguien toca para entrar a su cuarto, aparecerán aquí, esperando por su aprobación.',
  },
  webinar: {
    peersCount: {
      one: '%s persona está mirando',
      many: '%s personas están mirando',
    },
  },
  plugins: {
    by: 'de',
    size: 'Tamaño: %s kB',
    phSearch: 'buscar...',
    source: 'Código fuente:',
    apiDocs: 'Docs API',
    vendor: 'Vendedor:',
    btnAdd: 'Agregar propio',
    add: {
      title: 'Agregar plugin nuevo',
      descr: '⚙️ ¿Desarrollando un plugin nuevo? Agrégalo aquí para probar. No se guarda, al reinciar la página se borra de la memoria.',
      name: '¿Nombre del plugin?',
      rootUrl: '¿Dónde está la fuente del plugin?',
      loaded: '¡Sí! ¡Se cargó!',
      loadFailed: 'Falló la carga del plugin',
    }
  },
  help: {
    sevenTips: 'Top 7 Issues/Fixes',
    connIssues: 'Connection issues',
    laggyMedia: 'Laggy audio/video',
    unlockMedia: 'Unblock camera/mic',
    faq: 'Go to FAQ',
    submitFeature: 'Request a feature',
  },
}
