module.exports = {
  self: 'xroom',
  title: 'Your secure workspace',
  goToDash: 'Go to Dashboard',
  netStatus: 'איכות חיבור',
  buttons: {
    ok: 'אישור',
    cancel: 'ביטול',
    yes: 'כן',
    no: 'לא',
    chN: 'Choice %s',
    install: 'Add',
    uninstall: 'Remove',
    details: 'View details',
    close: 'Close',
    next: 'Next',
    back: 'Back',
    retry: 'Retry',
    dismiss: 'Dismiss',
    allow: 'Allow',
    stop: 'Stop',
    decideLater: 'Decide later',
    knock: 'דפוק בדלת',
    leave: 'יציאה',
  },
  mbox: {
    notSupported: 'It looks like this browser does not support this platform or WebRTC is disabled. 😢',
    protoExpired: 'The client version is too old. Please press Ctrl&nbsp;+&nbsp;Shift&nbsp;+&nbsp;F5 to reload. If you then see this message again, please clear your browser\'s cache manually.',
    areYouSure: 'Are you sure?',
    noPermission: 'Cannot acquire permissions from your browser. Please ensure that they are not blocked.',
    mediaBlocked: 'Camera access is blocked. Please ensure that you are not using it in another browser or program.',
    mediaError: 'You provided access to your hardware devices, but a local problem in your system prevented your device from being used. Please try another browser or another device.',
    whatIsYourName: 'מה שימך?',
    noPeersP2P: 'Messages do not use servers to send and cannot be redelivered after newly added guests connect. Please wait until others have joined the conversation to send messages.',
    noPeers: 'Messages cannot be redelivered after newly added guests connect. Please wait until others have joined the conversation to send messages.',
    password: 'צור ססמא לחדר',
    roomLocked: 'החדר נעול. אתה רוצה לדפוק בדלת כדי להכנס?',
    roomProtected: 'החדר נעול. אנא הכנס ססמא.',
    roomIsFull: 'החדר נעול. אנא נסה מאוחר יותר.',
    alreadyHosted: 'You are already in the room. You are probably testing with several browser tabs open at once. Do you want to enter? Host features may not work here.',
    youAreKicked: 'נזרקת מהחדר.',
    setQFailed: 'Failed to set the requested quality. Your hardware or browser may not support it.',
    bookingEnded: 'This booking is now over. The room is booked for another event, so you will now be redirected to another room to be able to finish your meeting.',
    bookingEndedHost: 'The current booking for this room is soon over. A choice must now be made as another booking has been scheduled using the same room name.<br/><br/>1. Go to a new meeting. We will direct you to the dashboard to enter the meeting with a new host key.<br/><br/>2. Stay in the meeting. We will create a new room for you to finish this call.',
    pluginsLoadFailed: 'Loading plugins failed',
    roomDestroyed: 'The room has been deleted. You will be redirected to the starting page.',
    encInfo: 'Encryption: end-to-end, ECDH+AES<br/>Hash: <code>%s</code>',
    encFailure: 'Encryption not supported',
    badBrowser: 'This user has a bad browser. Tell them not to use Safari or you may face bugs.',
    avaTooBig: 'Avatar file size is too big. Please use simple vector images instead.',
    cannotLoadPlugin: 'Plugin "%s" does not support your browser',
    confirmLeave: 'אתה בטוח שברצונך לעזוב את השיחה?',
    confirmDestroy: 'אתה בטוח שברצונך לסיים את השיחה לכל המשתתפים?',
    feedbackDetected: 'We have detected microphone feedback noises and muted you automatically. We suggest you use headphones or that you keep your mic off until you enter the room.',
    guestKnock: 'המשתמש <b>%s</b> רוצה להכנס לחדר. לאשר?<br/>תוכל להחליט מאוחר יותר בדף חדר ההמתנה.',
    safariNotSupported: 'This feature is temporarily not supported in Safari.',
    p2pNotSupported: 'This feature is disabled in peer-to-peer mode.',
    takeOverSharing: 'Sharing your screen now will end the current screen sharing session.',
    p2pInfo: 'P2P mode disables the use of our centralized servers.<br/><u>Room stability will then be dependent on your network.</u><br/>Recommended for private meetings of 2 people.',
    confirmKick: 'אתה בטוח שברצונך להסיר את %s מהחדר?',
    comingSoon: 'This feature is coming soon.',
    audioChanged: 'Input device added. Do you want to select which one to use now?',
    domainNotSetUp: 'This domain has not yet been set up. If you are its owner please do it in the dashboard. We will now forward you to our free service.',
    domainNotPaid: 'Your account has been temporarily deactivated due to not being current on payments. We will now forward you to our free service.',
    badLuck: 'Something went seriously wrong with the network. We will now try to reload your browser.',
    noEmbedding: 'Embedding protection is on. You may turn it off in the dashboard.',
    pluginSuggested: 'User %s suggested you to install plugin %s. Do you wish to do it?',
    noMoreRooms: 'Rooms limit is reached. Tell the owner to add more in the dashboard.',
  },
  notify: {
    slowPlugins: 'Too many plugins can cause slower loading times. Consider removing the largest.',
    peerLost: 'Reconnecting with %s...',
    roomLocked: 'החדר נעול 🔒',
    roomUnlocked: 'החדר פתוח 🔓',
    roomPwdSet: 'צור ססמא לחדר 🔑',
    roomPwdReset: 'Room password cleared',
    devicesChanged: 'Devices changed',
    hostMutedAudio: 'מנהל השתיק אותך',
    hostMutedVideo: 'מנהל סגר לך את המצלמה',
    incomingFile: 'Incoming file...',
  },
  upsell: {
    hd: 'HD video',
    notFree: '<b>%s</b> is only available with your own spaces. Try it right now for free.',
    startTrial: 'Start a trial',
    notInterested: 'Not interesting',
  },
  hint: {
    p2p: '<u>This platform</u> uses servers to ensure high quality transmissions during your meetings.<br/><br/>• We never have access to your communications in this mode.<br/><br/>• All data sent through our servers is encrypted and locked with keys only you and your guests have access to.<br/><br/><u>If you require maximum security,</u> you may disable our servers and instead use Peer-to-Peer mode.<br/><br/>• In this mode video and audio are sent directly between you and your guests without using sfu servers.<br/><br/>• We recommend using peer-to-peer mode when you anticipate having a 1:1 meeting.',
  },
  modes: {
    '1': 'קבוצתי - כולם יכולים לדבר',
    '2': 'וובינר - אחד מדבר והשאר מקשיבים',
  },
  placements: {
    '1': 'Grid view',
    '2': 'Mini-me',
    '3': 'Spotlight',
  },
  perm: {
    head: 'אשר הרשאות דפדפן',
    video: 'וידאו',
    audio: 'אודיו',
    notif: 'התראות',
  },
  videoMenu: {
    hint: 'Context menu',
    expand: 'Expand',
    pip: 'Keep on top',
    fullscreen: 'מסך מלא',
    fullscreenOff: 'יציאה ממסך מלא',
    volume: 'עוצמה',
    restore: 'Restore',
    kick: 'הסר משתתף',
    mute: 'Mute (only for you)',
    unmute: 'בטל השתקה',
    pm: 'ט פרטי',
    makeHost: 'הפוך למנהל',
  },
  controls: {
    sharing: 'Sharing',
    cam: 'מצלמה',
    mic: 'מיקרופון',
    chat: 'צט',
    exit: 'יציאה',
    destroy: 'סיים פגישה',
    settings: 'הגדרות',
    plugin: 'תוספים',
    dots: 'Context menu',
    invite: 'Invite',
    ss: 'שיתוף מסך',
    stopSharing: 'הפסק שיתוף',
    board: 'Whiteboard',
    hand: 'הרם יד',
    lock: 'נועל',
    layouts: 'Placement',
    emoji: 'סמיילים',
    attach: 'צרף קובץ',
    setLock: 'נעל את החדר',
    resetLock: 'פתח את החדר',
    setPwd: 'צור ססמא',
    rotate: 'מצלמה אחוריתקדמית',
    more: 'עוד',
    users: 'משתתפים',
  },
  reactions: {
    handRaised: 'User %s wants to speak 🎤',
  },
  video: {
    you: 'אורח (לחץ לשנות)',
    sharing: 'אתה משתף את המסך שלך',
  },
  settings: {
    tabs: {
      audio: 'אודיו',
      video: 'וידאו',
      general: 'כללי',
      help: 'עזרה',
      chat: 'צט',
      peers: 'משתתפים',
      lobby: 'חדר המתנה',
    },
    audioQ: 'קצב דגימה מקסימלי',
    videoQ: 'איכות וידאו מקסימלית',
    screenQ: 'איכות שיתוף מסך מקסימלית',
    bandwidthQ: 'פרופיל רוחב פס',
    soundEffects: 'אפקטים קוליים',
    audioDevices: 'מקורות שמע',
    videoDevices: 'מקורות וידאו',
    language: 'שפה',
    theme: 'ערכת צבעים',
    requestAudio: 'בקש הרדאת אודיו',
    requestVideo: 'בקש הרשאת וידאו',
    testOutput: 'בחן פלט קול',
    flipFace: 'הפוך כיוון מצלמה (אפקט מראה)',
    requireName: 'Require name',
    debug: 'Debug mode',
    noPreview: 'Start chats without preview',
    menuPos: 'Menu placement',
    menuPosO: {
      '1': 'top',
      '2': 'bottom',
    },
    name: 'קבעשנה את שם התצוגה שלך',
    phName: 'שימך',
  },
  home: {
    title: 'Your personal conference room',
    btnGo: 'Go!',
    nameRoom: 'name your room:',
    placeholder: 'type here',
    rejoinRoom: 'or rejoin',
    poweredBy: 'Powered by <a href="https://xroom.app">xroom.app</a>',
    roomHint: 'Enter room name please',
  },
  pre: {
    selectMode: 'בחר סגנון שיחה',
    selectedMode: 'סגנון שיחה',
    btnGo: 'כניסה',
    btnPreview: 'תצוגה מקדימה',
    avaPicker: 'בחר אווטאר (מופיע כשהמצלמה סגורה)',
    sizeLimitReached: 'This room is limited in size and the limit has been reached',
    roomBooked: 'There is going to be an event in this room soon: <span>%s</span>.<br/>Please stand by until the meeting begins.',
    roomInfo: 'Room info',
    phInfo: 'Enter room info',
    pendingAdmission: 'Please wait until the host lets you in.',
    p2pMode: 'Peer-to-peer mode',
    btnGoHome: 'Go to start page',
    btnAsHost: 'התחבר כמנהל',
    roomLocked: 'החדר ננעל על ידי מנהל.<br />אנא דפוק בדלת כדי להכנס.',
    roomLockedInfo: 'אנא הכנס את שימך.<br />אחרת מנהל לא יאשר את כניסתך.',
  },
  inviter: {
    info: 'Share the link below to invite others to the meeting.',
    head: 'Room link:',
    btnCopy: 'Copy link',
    btnShare: 'Share link',
    ntfCopied: 'The link has been copied!',
  },
  chat: {
    publicChat: 'Public chat',
    chatWith: 'Chat with %s',
    fileSending: 'Sending file: ',
    fileReceived: 'File received: ',
    phInput: 'Write a message...',
    me: 'me',
    dropMe: 'Drop me!',
    atTime: 'at %s',
    recvProgress: 'receiving encrypted data: %s%...',
  },
  peers: {
    muteOnEntry: 'Mute participants on entry',
    camsOff: 'Turn off all videos',
    micsOff: 'Mute all',
  },
  knockers: {
    phEmpty: 'If someone knocks to enter your room they will appear here, waiting for your approval.',
  },
  webinar: {
    peersCount: {
      one: '%s person is watching',
      many: '%s persons are watching',
    },
  },
  plugins: {
    by: 'by',
    size: 'Size: %s kB',
    phSearch: 'search...',
    source: 'Source code: ',
    apiDocs: 'API docs',
    vendor: 'Vendor:',
    btnAdd: 'Add own',
    add: {
      title: 'Add new plugin',
      descr: '⚙️ Developing a new plugin? Add it here to test. It is not saved anywhere, but in your browser.',
      name: 'What\'s the plugin name?',
      rootUrl: 'Where is the plugin root?',
      loaded: 'Yaay! It\'s loaded!',
      loadFailed: 'Failed loading plugin',
    }
  },
  help: {
    sevenTips: 'Top 7 Issues/Fixes',
    connIssues: 'Connection issues',
    laggyMedia: 'Laggy audio/video',
    unlockMedia: 'Unblock camera/mic',
    faq: 'Go to FAQ',
    submitFeature: 'Request a feature',
  },
}
