export default {
  self: 'xroom',
  on: 'Accesa',
  off: 'Spenta',
  title: 'Ti serve una stanza conferenze?',
  buttons: {
    ok: 'Ok',
    yes: 'Si',
    no: 'No',
    cancel: 'Annulla',
    retry: 'Riprova',
    chooseWindow: 'Scegli una finestra',
    wholeScreen: 'Schermo intero',
    install: 'Aggiungi',
    uninstall: 'Rimuovi',
    send: 'Invia',
    close: 'Chiudi',
    hide: 'Nascondi',
    knock: 'Toc toc',
    allowIn: 'Accesso consentito',
    deny: 'Accesso negato',
  },
  mbox: {
    notSupported: 'Sembra che questo browser non supporti XROOM o WebRTC sia disabilitato.',
    success: 'Operazione riuscita',
    failure: 'Operazione fallita',
    enterRoomName: 'Inserisci il nome della stanza per favore',
    isCamOn: 'La videocamera e accesa?',
    isCamOnText: 'Per favore verifica di non aver bloccato per sbaglio la videocamera/il microfono su questo sito e premi "Riprova".',
    isMicOn: 'Il microfono e acceso?',
    isMicOnText: 'Se vuoi parlare, abbiamo bisogno del tuo permesso per il microfono. Dai il consenso su questa pagina e premi "Riprova".',
    iWillOnlyWatch: 'Solo video',
    iWillOnlyListen: 'Solo audio',
    screenSharingText: 'La condivisione dello schermo non e consentita. Assicurati che non sia bloccata per questa pagina.<br><br>Anche questa funzione e supportata solo da browser aggiornati come Chrome o Firefox.',
    cannotFile: 'Dato che non possiamo accedere nemmeno ai tuoi file, non possiamo inviarli dopo che qualcuno si e connesso. Devi farlo online.',
    cannotMessage: 'Dato che non possiamo accedere nemmeno ai tuoi messaggi, non possiamo inviarli dopo che qualcuno si e connesso. Devi farlo online.',
    roomLockedText: 'Questa stanza e bloccata',
    oops: 'Scusa',
    kickedOutText: 'Sei stato buttato fuori',
    areYouSure: 'Sei sicuro?',
    doYouWantToLeave: 'Sei sicuro di voler uscire?',
    doYouWantToLeaveAsHost: 'Sei sicuro di voler interrompere lo streaming?',
    restartRequiredText: 'Questa impostazione influenza troppe cose, e necessario ricaricare la pagina. Ci mette un attimo, non ti preoccupare!',
    onlySafariOnIOS: 'iOS supporta solo Safari. "Grazie", Apple!',
    cannotLoadPlugin: 'Plugin "%s" non supporta il tuo browser',
    confirmFileSend: 'Vuoi inviarlo?',
    whatIsYourName: 'Inserisci un nuovo nome',
    setVideoVolume: 'Imposta il volume per questo video',
    roomLockedTryKnockText: 'La stanza e attualmente bloccata. Puoi chiedere il permesso di entrare "bussando" alla porta.',
    knockingFailedText: 'Tentativo di bussata fallito',
    doYouWantToKick: 'Sei sicuto di voler cacciare questo utente?',
    deviceChanged: 'Hai collegato/rimosso un nuovo dispositivo di input. Se non funziona, selezionalo manualmente da Impostazioni.',
    allowCameraPlz: 'Dopo aver premuto Ok per favore <b>dai il consenso</b> a xroom di usare la tua videocamera.<br><br>Non preoccuparti! Sarai in grado di spegnerla di nuovo prima di entrare nella stanza dal menu in basso, se vuoi rimanere non visibile.',
    tooOldBrowser: 'Il tuo browser non e supportato o e prodotto da Microsoft. Molte funzioni potrebbero non essere disponibili.',
    pluginsLoadFailed: 'Caricamento dei plugin non riuscito',
    researchConsent: 'Ciao! Stiamo effettuando una ricerca sulle reti p2p.<br><br>Ci autorizzi a utilizzare le informazioni sulla qualita del traffico per una ricerca?',
  },
  home: {
    nisdos: 'Non usiamo i cookie',
    title: 'La tua sala conferenze personale',
    btnGo: 'Vai!',
    knowMore: 'Informazioni su xroom',
    nameRoom: 'Inserisci il nome della tua stanza:',
    placeholder: 'digita qui',
    rejoinRoom: 'o riunisciti',
  },
  wl: {
    poweredBy: 'Offerto da',
  },
  pre: {
    checkIt: 'Controlla il tuo microfono e le cuffie',
    btnGo: 'Entra',
    knockDenied: 'La tua richiesta di bussata e stata respinta. Non puoi entrare nella stanza. :(',
    knockRequested: 'In attesa di permesso. Le persone possono vederti attraverso uno spioncino.',
    noAudio: 'Nessun segnale dal microfono rilevato',
    roomIsBusyWebinar: 'Un webinar/streaming e attualmente in corso',
    roomIsBusyConference: 'Una conferenza e attualmente in corso',
    startWebinar: 'Avvia in modalita streaming/webinar',
  },
  videoMenu: {
    hint: 'Attiva/disattiva menu',
    expand: 'Espandi',
    fullscreen: 'Schermo intero',
    volume: 'Volume A}',
    restore: 'Ripristina',
    kick: 'Caccia',
  },
  controls: {
    ss: 'Condivisione schermo %s',
    cam: 'Videocamera %s',
    mic: 'Microfono %s',
    chat: 'Chat %s',
    exit: 'Esci',
    xroom: 'Offerto da xroom',
    settings: 'Impostazioni',
    plugins: 'Plugin',
    media: 'Media',
    reactions: 'Intenzione',
    letMeSpeak: 'Fammi parlare',
  },
  reactions: {
    letMeSpeak: 'Voglio parlare!',
  },
  waiting: {
    invite: 'Invita i tuoi colleghi',
    beforeCopy: 'Clicca per copiare',
    afterCopy: 'Copiato!',
    webinar: 'Il Webinar non e ancora iniziato',
  },
  video: {
    you: 'Tu',
    someone: 'Qualcuno',
    knocking: 'stai bussando...',
    poorNet: 'Connessione lenta',
  },
  chat: {
    fileSending: 'Invio file: ',
    fileReceived: 'File ricevuto: ',
    inputPlaceholder: 'Digita un messaggio and premi invio ...',
    me: 'me',
    dropMe: 'Scrivimi!',
  },
  webinar: {
    peersCount: '%s persone stanno guardando',
  },
  settings: {
    experimental: '*) sperimentale, funziona in modo instabile',
    showCameraWithScreen: 'Moastra la videocamera durante la condivisione dello schermo *',
    qualityLevel: 'Qualita alta (utilizza piu traffico)',
    autoGetIn: 'Avvia chat senza anteprima',
    soundEffects: 'Effetti sonori',
    noisyBackground: 'Sono in un posto rumoroso',
    rtcDebug: 'Debug RTC',
    audioDevices: 'Fonti audio',
    videoDevices: 'Fonti video',
    language: 'Lingua',
    theme: 'Colore tema',
  },
  plugins: {
    by: 'da',
    size: 'dimensione: %s kB',
    searchPlaceholder: 'Ricerca in corso...',
    source: 'Codice sorgente',
    add: {
      title: 'Aggiungi un nuovo plugin',
      descr: 'Stai sviluppando un nuovo plugin? Aggiungilo qui per testarlo. Non e stato salvato, ricaricando la pagina viene rimosso dalla memoria. Il manuale dei plugin API e disponibile <a href="https://github.com/punarinta/xroom-plugins" target="_blank">qui</a>.',
      name: 'Qual e il nome del plugin?',
      rootUrl: 'Dov`e il plugin root?',
      loaded: 'Evviva! Caricamento riuscito!',
      loadFailed: 'Caricamento del plugin fallito',
    }
  },
  feedback: {
    header: 'Oh, scusa, solo un attimo...',
    question: 'Questa volta e andato tutto bene?',
    videoFroze: 'No, video bloccato',
    soundLagged: 'No, audio rallentato',
    cantConnect: 'No, qualcuno non e riuscito a connettersi',
    smthElse: 'Qualcos`altro:',
    feedbackInput: 'lascia il feedback...',
    contactMe: 'Contattami per favore:',
    emailInput: 'la tua email...',
  },
  tips: {
    prefix: 'Consiglio del giorno: ',
    lines: [
      'Attivi/disattivi l`audio spesso? C`e il tasto di scelta rapida "m" per quello.',
      'Fai doppio clic su un video remoto per visualizzarlo a schermo intero.',
      'Hai bisogno di chiudere la tua stanza? Aggiungi semplicemente il blocco della stanza nei plugin di seguito.',
      'Usa Slack e vuoi risparmiare piu tempo? Prova il nostro <a href="//about.xroom.app/en/library/slack-bot" target="_blank">bot di Slack</a>.',
      'Perdi le videochiamate su Telegram? Il nostro <a href="//about.xroom.app/en/library/telegram-bot" target="_blank">bot di Telegram</a> e qui per aiutarti.',
      'Devi condividere un`immagine copiata? Fai Ctrl+V nella chat, noi penseremo al resto.',
      'Clicca sul tuo nome per modificarlo sia localmente che per i tuoi colleghi.',
      'Hai mai avuto bisogno di registrare il tuo schermo con pochi clic? Prova il nostro plug-in per la registrazione dello schermo.',
      'Devi disegnare durante una chiamata? prova il plug-in di disegno. Non dimenticare di attivare la condivisione dello schermo.',
      'Clicca sul tuo nome o "Tu" per rinominare te stesso per tutti.',
    ]
  },
}
