export default {
  self: 'xroom',
  on: '(+)',
  off: '(–)',
  title: 'Potrěbuješ svojų vlastnų konfų?',
  buttons: {
    ok: 'Dobro',
    yes: 'Da',
    no: 'Ne',
    cancel: 'Anuluj',
    retry: 'Iznova',
    chooseWindow: 'Izbraj okno',
    wholeScreen: 'Cěly ekran',
    install: 'Pridaj',
    uninstall: 'Izbavi',
    send: 'Izsľ mněnje',
    close: 'Zatvori',
    hide: 'Ukryi',
    knock: 'Stukni',
    allowIn: 'Dozvoli',
    deny: 'Odkaži',
    enterAnyway: 'Enter anyway',
  },
  mbox: {
    notSupported: 'Kaže sę, že tuta prěględka ne poddŕživaje XROOM, abo WebRTC je nedějųći. 😢',
    success: 'Udalo sę',
    failure: 'Ne udalo sę',
    enterRoomName: 'Podaj nazvų komnaty, prosim',
    isCamOn: 'Či kamera rabotna?',
    isCamOnText: 'Prosim prověriti, že kamera/mikrofon ne sųt slučajno zablokovane, i potom kliknuti "Iznova".',
    isMicOn: 'Či mikrofon rabotny?',
    isMicOnText: 'Jestli planuješ govoriti togda potrěbujemo dostup do tvojego mikrofona. Dozvoli to na sej stranici i klikni "Iznova".',
    iWillOnlyWatch: 'Ja toliko bųdų gleděti',
    iWillOnlyListen: 'Ja toliko bųdų slušati',
    screenSharingText: 'Děľeńje ekrana ne je dozvoľeno. Prosim prověriti, že ono ne je zablokovane na sej stranici.<br><br>Takože sa sposobnosť toliko poddŕživama modernymi web-prěględkami kako Chrome, Firefox, Yandex i t.d.',
    cannotFile: 'Zato že ne dŕžamo tvoje fajly, ne možemo dostaviti jih kogda někto svęže sę. Potrěbuješ sdělati to sam/a on-line.',
    cannotMessage: 'Zato že ne dŕžamo tvoje poslańja, ne možemo dostaviti jih kogda někto svęže sę. Potrěbuješ sdělati to sam/a on-line.',
    roomLockedText: 'Tojta komnata je zamknena',
    oops: 'Izvinite',
    kickedOutText: 'Tebe izphnųli iz komnaty',
    areYouSure: 'Jesi uvěrjen?',
    doYouWantToLeave: 'Či napravdu hočeš izidti?',
    doYouWantToLeaveAsHost: 'Či napravdu hočeš obstanoviti strim?',
    restartRequiredText: 'Tuta nastavka ovplyvnjaje prěmnogo, potrěbno je prěsčitati stranicų. Ale to bųde bystro, ne trevoži sę.',
    onlySafariOnIOS: 'V iOS poddŕživajemo toliko Safari. "Blågodarimo", Apple!',
    cannotLoadPlugin: 'Dodatok "%s" ne rabotaje v tvojej prěględkě.',
    confirmFileSend: 'Hćeš odslati to?',
    whatIsYourName: 'Podaj nove ime',
    setVideoVolume: 'Nastavi vysotų zvųka tutojego video',
    roomLockedTryKnockText: 'Komnata zamknena. Možeš poprositi pozvaljańja vstųpiti posrědstvom "stukańje" do dvere.',
    knockingFailedText: 'Knocking attempt failed',
    doYouWantToKick: 'Hočeš izphnuti sego koristnika?',
    deviceChanged: 'Bylo dodano nove orųďje vvoda. Jestli ono ne råbotaje, otvori Nastavki i izberi jego rųčno.',
    allowCameraPlz: 'Po tiskańja tipky "Dobro" <b>dozvoli</b>, prosimo, xroom koristati kamerų.<br><br>Ne trevoži sę, jestli ne hočeš že by te viděli, možno bųde bez problemov zamknųti jų pozdněje.',
    tooOldBrowser: 'Tvoja prěględka je zastarěla abo je proizvedena v Microsoft. Mnoge funkcije mogųt ne råbotati.',
    pluginsLoadFailed: 'Failed loading plugins',
    protoExpired: 'Too old client version. Please press Ctrl&nbsp;+&nbsp;Shift&nbsp;+&nbsp;F5 to reload. If you then see this message again please clear browser cache manually.',
    peerError: 'Something went wrong when exchanging data with your peers. We suggest reloading the page.',
    enterpriseOnly: 'This is an enterprise only feature.',
    pluginSuggested: 'User %s suggested you to install plugin %s. Do you wish to do it?',
    hostRoleRequired: 'Host role is required for this action.',
    alreadyHosted: 'Room is already hosted. Do not enter the same room from 2 browser tabs. 😉',
    roomLockedPassword: 'Room is currently locked with a password. Enter it below if you know it.',
  },
  home: {
    nisdos: 'Ne upotrěbjamo "cookies"',
    title: 'Tvoja vlastna web-konferencija',
    btnGo: 'Hodimo!',
    knowMore: 'Ob xroom',
    nameRoom: 'nazovi komnatų:',
    placeholder: 'piši tu',
    rejoinRoom: 'abo vstupi iznova v',
  },
  wl: {
    poweredBy: 'Råbotaje na ',
  },
  modes: {
    1: 'Konferencija',
    2: 'Webinar',
  },
  pre: {
    selectMode: 'Izberi režim komnaty',
    checkIt: 'Prověri svoj mikrofon i kamerų',
    btnGo: 'Vstupi',
    knockDenied: 'Your knock request has been denied. You can`t enter the room. :(',
    knockRequested: 'Čekajemo pozvaljańja vstųpiti. Drugi mogųt viděti te črěz podględanok. 👀',
    noAudio: '⚠️ Ne čujemo zvųkovogo signala',
    roomIsBusyWebinar: 'Webinar/strim už ide (%s × 🙂)',
    roomIsBusyConference: 'Web-konferencija už ide (%s × 🙂)',
  },
  videoMenu: {
    hint: 'Phni menu',
    expand: 'Razširi',
    fullscreen: 'Polny ekran',
    volume: 'Zvųk ±',
    restore: 'Menši',
    kick: 'Izphni',
  },
  controls: {
    ss: 'Ekran %s',
    cam: 'Obraz %s',
    mic: 'Zvųk %s',
    chat: 'Čat %s',
    exit: 'Izhod',
    xroom: 'Sdelano iz xroom',
    settings: 'Nastavki',
    plugins: 'Dodatki',
    media: 'Media',
    more: 'Ješče',
    letMeSpeak: 'Pozvoli mi rěkti',
  },
  reactions: {
    letMeSpeak: 'Ja hoćų mòlviti!',
  },
  waiting: {
    invite: 'Pozovi svojih koleg',
    beforeCopy: 'klikni da by kopirovati',
    afterCopy: 'kopirovano!',
    webinar: 'Webinar ješče ne načel sę',
  },
  video: {
    you: 'Ty',
    someone: 'Někto',
    knocking: 'stukaje...',
    poorNet: 'zla svez',
  },
  chat: {
    fileSending: 'Sľemo fajl: ',
    fileReceived: 'Prijeny fajl: ',
    inputPlaceholder: 'natipkaj poslanje i natiskni "enter" ...',
    me: 'ja',
    dropMe: 'Opusti mi!',
  },
  webinar: {
    peersCount: '%s ljudi zrějųt',
  },
  settings: {
    experimental: '*) probno, rabotaje nestabilno',
    showCameraWithScreen: 'Pokazyvati svoj obraz v tečenju děľeńja ekrana *',
    qualityLevel: 'Vysoky kvalitet (koristaje vyše trafik)',
    autoGetIn: 'Otvarjati čaty bez podględa',
    soundEffects: 'Zvųkove efekty',
    noisyBackground: 'Ja v šumnym městu',
    rtcDebug: 'Dobrostaviti RTC',
    audioDevices: 'Žrla zvųka',
    videoDevices: 'Žrla obraza',
    language: 'Język',
    theme: 'Kolorna tema',
    server: 'Server',
  },
  plugins: {
    by: 'od',
    size: 'veličina: %s kB',
    searchPlaceholder: 'išči...',
    source: 'Žrlokod',
    add: {
      title: 'Dodati novy dodatok',
      descr: '⚙️ Izråbotyvaješ novy dodatok? Dodaj jego tu da by testovati. Ne zapisyvajemo jego, jestli prědostaješ strånicų on iznikne iz pamęti. Prirųčnik API dodatkov je dostųpny <a href="https://github.com/punarinta/xroom-plugins" target="_blank">tutaj</a>.',
      name: 'Kaka je nazva dodatka?',
      rootUrl: 'Kde je root URL dodatka?',
      loaded: 'Lěpo! On je vniknųl!',
      loadFailed: 'Grěška vnikneńja dodatka',
    }
  },
  feedback: {
    header: 'Oj, toliko sekundų, prosim...',
    question: 'Vsečto bylo dobre?',
    videoFroze: 'Ne, video mrazilo sę',
    soundLagged: 'Ne, zvųk lagged',
    cantConnect: 'Ne, někto ne smogl sjediniti sę',
    smthElse: 'Inočto:',
    feedbackInput: 'ostavi mněnje',
    contactMe: 'Napišite do mně:',
    emailInput: 'moj email',
  },
  tips: {
    prefix: 'Sovět dnja: ',
    lines: [
      'Često němeješ mikrofon? Zato imajemo klaviš "m".',
      'Dvuklikni oddaljeno video da by vključiti polny ekran.',
      'Potrěba zamknuti komnatų? Prosto dodaj "room locking" v dodatkah poniže.',
      'koristaješ Slack i hočeš poščediti vręme? Poprobuj naš <a href="//about.xroom.app/en/library/slack-bot" target="_blank">Slack bot</a>.',
      'Nedostavaješ video v Telegramu? Naš <a href="//about.xroom.app/en/library/telegram-bot" target="_blank">Telegram bot</a> pomože tobě.',
      'Potrěba děliti kopirovany obraz? Ctrl+V v čatu, sdělamo ostatok.',
      'Klikni svoje ime da by izměniti jego kako męstno tako i oddaljeno.',
      'Kogda-nebud trěboval zapisyvati ekran parojų klikov? Poprobuj naš dodatok dlja zapisa ekranu.',
    ]
  },
}
