export default {
  self: 'xroom',
  on: '(+)',
  off: '(–)',
  title: 'Potrěbuješ svojų vlastnų konfų?',
  buttons: {
    ok: 'Dobro',
    yes: 'Da',
    no: 'Ne',
    cancel: 'Anuluj',
    retry: 'Iznova',
    chooseWindow: 'Izbraj okno',
    wholeScreen: 'Cěly ekran',
    install: 'Pridaj',
    uninstall: 'Izbavi',
    send: 'Izsľ mněnje',
    close: 'Zatvori',
    hide: 'Ukryi',
    knock: 'Stukni',
    allowIn: 'Dozvoli',
    deny: 'Odkaži',
  },
  mbox: {
    success: 'Udalo sę',
    failure: 'Ne udalo sę',
    enterRoomName: 'Podaj nazvų komnaty, prosim',
    isCamOn: 'Či kamera rabotna?',
    isCamOnText: 'Prosim prověriti, že kamera/mikrofon ne sųt slučajno zablokovane, i potom kliknuti "Iznova".',
    isMicOn: 'Či mikrofon rabotny?',
    isMicOnText: 'If you plan to talk we need your mic permission. Allow it on this page and press "Iznova".',
    iWillOnlyWatch: 'Ja toliko bųdų gleděti',
    iWillOnlyListen: 'Ja toliko bųdų slušati',
    screenSharingText: 'Screen sharing is not allowed. Please ensure it is not blocked for this page.<br><br>Also this feature is only supported by modern browsers like Chrome or Firefox.',
    cannotFile: 'Since we don\'t even touch your files we cannot deliver them after someone connects. You need to do it online.',
    cannotMessage: 'Since we don\'t even touch your messages we cannot deliver them after someone connects. You need to do it online.',
    roomLockedText: 'Tojta komnata je zamknena',
    oops: 'Izvinite',
    kickedOutText: 'You have been kicked out',
    areYouSure: 'Jesi uvěrjen?',
    doYouWantToLeave: 'Či napravdu hočeš izidti?',
    restartRequiredText: 'This setting affects to much stuff, a so a reload is required. That\'s quick, don\'t worry!',
    onlySafariOnIOS: 'On iOS only Safari is supported. "Thank you", Apple!',
    cannotLoadPlugin: 'Plugin "%s" does not support your browser',
    confirmFileSend: 'Do you want to send this?',
    whatIsYourName: 'Podaj nove ime',
    setVideoVolume: 'Set volume for this video',
    roomLockedTryKnockText: 'Room is currently locked. You can ask for a permission to enter by "knocking" the door.',
    knockingFailedText: 'Knocking attempt failed',
    doYouWantToKick: 'Hočeš izphnuti sego koristnika?',
    deviceChanged: 'You have attached/removed a new input device. If it does not work choose it manually from Settings.',
  },
  home: {
    nisdos: 'Ne upotrěbjamo "cookies"',
    title: 'Tvoja vlastna konferencija',
    btnGo: 'Hodi!',
    knowMore: 'Ob xroom',
    placeholder: 'tvoja komnata',
    rejoinRoom: 'abo vstupi iznova',
  },
  wl: {
    poweredBy: 'Powered by ',
  },
  pre: {
    checkIt: 'Prověri svoj mikrofon i kamerų',
    btnGo: 'Vstupi',
    knockDenied: 'Your knock request has been denied. You can\'t enter the room. :(',
    knockRequested: 'Awaiting for a permission. People can see you through a peephole. 👀',
    noAudio: '⚠️ No audio signal detected',
  },
  videoMenu: {
    hint: 'Phni menu',
    expand: 'Razširi',
    fullscreen: 'Polny ekran',
    volume: 'Zvuk ±',
    restore: 'Menši',
    kick: 'Izphni',
  },
  controls: {
    ss: 'Děľeńje ekrana %s',
    cam: 'Kam %s',
    mic: 'Mik %s',
    chat: 'Čat %s',
    exit: 'Izhod',
    xroom: 'Sdelano iz xroom',
    settings: 'Nastavki',
    plugins: 'Dodatki',
  },
  waiting: {
    invite: 'Pozovi svojih koleg',
    beforeCopy: 'klikni da by kopirovati',
    afterCopy: 'kopirovano!',
    webinar: 'Webinar not started yet',
  },
  video: {
    you: 'Ty',
    someone: 'Někto',
    knocking: 'stukaje...',
  },
  chat: {
    fileSending: 'Sľemo fajl: ',
    fileReceived: 'Prijeny fajl: ',
    inputPlaceholder: 'natipkaj poslanje i natiskni "enter" ...',
    me: 'ja',
    dropMe: 'Opusti mi!',
  },
  webinar: {
    peersCount: '%s people are watching',
  },
  settings: {
    experimental: '*) probno, rabotaje nestabilno',
    showCameraWithScreen: 'Pokazyvati kamerų v tečenju děľeńja ekrana *',
    qualityLevel: 'Vysoky kvalitet (koristaje vyše trafik)',
    autoGetIn: 'Otvarjati čaty bez podgleda',
    soundEffects: 'Zvukove efekty',
    noisyBackground: 'Ja v šumnym městu',
    audioDevices: 'Audio sources',
    videoDevices: 'Video sources',
  },
  plugins: {
    by: 'od',
    size: 'veličina: %s kB',
    searchPlaceholder: 'išči...',
    add: {
      title: 'Add new plugin',
      descr: '⚙️ Developing a new plugin? Add it here to test. It is not saved, reloading the page removes it from memory. Plugins API manual is available <a href="https://github.com/punarinta/xroom-plugins" target="_blank">here</a>.',
      name: 'What\'s the plugin name?',
      rootUrl: 'Where is the plugin root?',
      loaded: 'Yaay! It\'s loaded!',
      loadFailed: 'Failed loading plugin',
    }
  },
  feedback: {
    header: 'Oj, toliko sekundų, prosim...',
    question: 'Vsečto bylo dobre?',
    videoFroze: 'Ne, video mrazilo sę',
    soundLagged: 'Ne, zvuk lagged',
    cantConnect: 'Ne, někto ne smogl sjediniti sę',
    smthElse: 'Inočto:',
    feedbackInput: 'ostavi mněnje',
    contactMe: 'Napišite do mně:',
    emailInput: 'moj email',
  },
  tips: {
    prefix: 'Sovět dnja: ',
    lines:[
      'Često němeješ mikrofon? Zato imajemo klaviš "m".',
      'Dvuklikni oddaljeno video da by vključiti polny ekran.',
      'Potrěba zamknuti komnatų? Prosto dodaj "room locking" v dodatkah poniže.',
      'koristaješ Slack i hočeš poščediti vręme? Poprobuj naš <a href="//about.xroom.app/en/library/slack-bot" target="_blank">Slack bot</a>.',
      'Nedostavaješ video v Telegramu? Naš <a href="//about.xroom.app/en/library/telegram-bot" target="_blank">Telegram bot</a> pomože tobě.',
      'Potrěba děliti kopirovany obraz? Ctrl+V v čatu, sdělamo ostatok.',
      'Klikni svoje ime da by izměniti jego kako męstno tako i oddaljeno.',
    ]
  },
}
