module.exports = {
  self: 'xroom',
  title: 'Jouw beveiligde werkruimte',
  goToDash: 'Ga naar Dashboard',
  netStatus: 'Connectie',
  buttons: {
    ok: 'Oké',
    cancel: 'Annuler',
    yes: 'Ja',
    no: 'Nee',
    chN: 'Keuze %s',
    install: 'Voeg Toe',
    uninstall: 'Verwijder',
    details: 'Bekijk details',
    close: 'Sluit',
    next: 'Volgende',
    back: 'Terug',
    retry: 'Opnieuw Proberen',
    dismiss: 'Afwijzen',
    allow: 'Toestaan',
    stop: 'Stop',
    decideLater: 'Beslis later',
    knock: 'Aankloppen',
    leave: 'Verlaten',
  },
  mbox: {
    notSupported: 'Het ziet ernaar uit dat deze browser dit platform niet ondersteunt of WebRTC is uitgeschakeld. 😢',
    protoExpired: 'De clientversie is te oud. Gelieve Ctrl&nbsp;+&nbsp;Shift&nbsp;+&nbsp;F5 te drukken om te herladen. Als je dit bericht opnieuw ziet, gelieve dan je browser cache manueel te wissen.',
    areYouSure: 'Ben je zeker?',
    noPermission: 'Kan geen toegang verkrijgen van je browser. Gelieve te verzekeren dat ze niet geblokkeerd worden.',
    mediaBlocked: 'Camera toegang is geblokkeerd. Gelieve te verzekeren dat je deze niet gebruikt in een ander browser of programma.',
    mediaError: 'Je hebt toegang gegeven tot je hardware toestellen, maar een lokaal probleem in je systeem voorkomt het gebruik van je toestel. Gelieve een ander browser of toestel te proberen.',
    whatIsYourName: 'Wat is je naam?',
    noPeersP2P: 'Berichten gebruiken geen servers om te verzenden en kan niet opnieuw worden afgeleverd nadat nieuw toegevoegde gasten verbinding hebben gemaakt. Wacht tot anderen zich bij het gesprek hebben aangesloten om berichten te verzenden.',
    noPeers: 'Berichten kunnen niet opnieuw worden bezorgd nadat nieuw toegevoegde gasten verbinding hebben gemaakt. Wacht tot anderen zich bij het gesprek hebben aangesloten om berichten te verzenden.',
    password: 'Stel ruimte wachtwoord in.',
    roomLocked: 'Deze ruimte is vergrendeld. Wil je aankloppen om erin te geraken?',
    roomProtected: 'Deze ruimte is beschermd met een wachtwoord. Gelieve het hieronder in te geven.',
    roomIsFull: 'De ruimte is volzet. Je kan niet naar binnen.',
    alreadyHosted: 'Je bent al in de ruimte. Je bent waarschijnlijk aan het testen met meerdere browsertabbladen tegelijk geopend. Wil je binnenkomen? Beheerderfuncties werken hier mogelijk niet.',
    youAreKicked: 'Je werd uit deze ruimte gezet.',
    setQFailed: 'Kan de gevraagde kwaliteit niet instellen. Je hardware of browser ondersteunt dit mogelijk niet.',
    bookingEnded: 'Deze boeking is nu voorbij. De ruimte is geboekt voor een ander evenement, dus je wordt nu doorgestuurd naar een andere ruimte om je vergadering te kunnen beëindigen.',
    bookingEndedHost: 'De huidige boeking voor deze ruimte is binnenkort afgelopen. Er moet nu een keuze worden gemaakt omdat er een andere boeking is gepland met dezelfde ruimtenaam.<br/><br/>1. Ga naar een nieuwe vergadering. We zullen je naar het dashboard leiden om de vergadering binnen te gaan met een nieuwe hostsleutel.<br/><br/>2. Blijf in de vergadering. We zullen een nieuwe kamer voor je maken om dit gesprek af te ronden.',
    pluginsLoadFailed: 'Laden van plugins gefaald.',
    roomDestroyed: 'De ruimte is verwijderd. Je wordt doorgestuurd naar de startpagina.',
    encInfo: 'Encryptie: end-to-end, ECDH+AES<br/>Hash: <code>%s</code>',
    encFailure: 'Encryptie niet ondersteund',
    badBrowser: 'Deze gebruiker heeft een slechte browser. Zeg hen Safari niet te gebruiken, anders kunnen er fouten optreden.',
    avaTooBig: 'Avatar bestandsgrootte is te groot. Gelieve eenvoudige vector afbeeldingen te gebruiken.',
    cannotLoadPlugin: 'Plugin "%s" ondersteunt je browser niet',
    confirmLeave: 'Ben je zeker dat je het gesprek wilt verlaten?',
    confirmDestroy: 'Ben je zeker dat je de vergadering voor alle deelnemers wilt beëindigen?',
    feedbackDetected: 'We hebben feedbackgeluiden van de microfoon gedetecteerd en je automatisch gedempt. We raden je aan een hoofdtelefoon te gebruiken of je microfoon uit te houden totdat je de kamer binnenkomt.',
    guestKnock: 'Gebruiker <b>%s</b> wilt naar binnen. Toestaan?<br/>Je kan later beslissen in het wachtruimte tabblad.',
    safariNotSupported: 'Deze functie is tijdelijk niet ondersteund in Safari.',
    p2pNotSupported: 'Deze functie is uitgeschakeld in peer-to-peer modus.',
    takeOverSharing: 'Het delen van je scherm nu zal de huidige scherm delen sessie beëindigen.',
    p2pInfo: 'De P2P-modus schakelt het gebruik van onze gecentraliseerde servers uit.<br/><u>De stabiliteit van de ruimte is dan afhankelijk van jouw netwerk.</u><br/>Aanbevolen voor privévergaderingen van 2 personen.',
    confirmKick: 'Ben je zeker dat je %s uit deze ruimte wilt verwijderen?',
    comingSoon: 'Deze functie komt binnenkort.',
    audioChanged: 'Invoerapparaat toegevoegd. Wil je kiezen welke je nu wilt gebruiken?',
    domainNotSetUp: 'Dit domein is nog niet ingesteld. Als je de eigenaar bent, doe dit dan in het dashboard. We sturen je nu door naar onze gratis service.',
    domainNotPaid: 'Je account is tijdelijk gedeactiveerd omdat de betalingen niet actueel zijn. We sturen je nu door naar onze gratis service.',
    badLuck: 'Er is iets ernstig misgegaan met het netwerk. We zullen nu proberen je browser opnieuw te laden.',
    noEmbedding: 'Bescherming tegen insluiten is ingeschakeld. Je kan dit uitschakelen in het dashboard.',
    pluginSuggested: 'Gebruiker %s stelde je voor om de plugin %s te installeren. Wens je dit te doen?',
    noMoreRooms: 'De limiet van de ruimtes is bereikt. Zeg de eigenaar om er meer toe te voegen in het dashboard.',
  },
  notify: {
    slowPlugins: 'Te veel plugins kunnen langzamere laadtijden veroorzaken. Overweeg om de grootste te verwijderen.',
    peerLost: 'Opnieuw connecteren met %s...',
    roomLocked: 'Ruimte vergrendeld 🔒',
    roomUnlocked: 'Ruimte ontgrendeld 🔓',
    roomPwdSet: 'Ruimte wachtwoord ingesteld 🔑',
    roomPwdReset: 'Ruimte wachtwoord gewist',
    devicesChanged: 'Toestellen veranderd',
    hostMutedAudio: 'Beheerder heeft je microfoon gedempt',
    hostMutedVideo: 'Beheerder heeft je camera uitgeschakeld',
    incomingFile: 'Inkomend bestand...',
  },
  upsell: {
    hd: 'HD video',
    notFree: '<b>%s</b> is alleen beschikbaar met je eigen ruimtes. Probeer het nu gratis.',
    startTrial: 'Start een proefperiode',
    notInterested: 'Niet interessant',
  },
  hint: {
    p2p: '<u>Dit platform</u> gebruikt servers om overdracht van hoge kwaliteit tijdens je vergaderingen te garanderen.<br/><br/>• We hebben nooit toegang tot je communicatie in deze modus.<br/><br/>• Alle gegevens die via onze servers worden verzonden, zijn versleuteld en vergrendeld met sleutels waar alleen jij en je gasten toegang toe hebben.<br/><br/><u>Als je maximale beveiliging nodig hebt,</u> kan je onze servers uitschakelen en in plaats daarvan de peer-to-peer modus gebruiken.<br/ ><br/>• In deze modus worden video en audio rechtstreeks tussen jou en je gasten verzonden zonder sfu-servers te gebruiken.<br/><br/>• We raden aan om de peer-to-peer modus te gebruiken als je verwacht 1-op-1 vergaderingen te houden.',
  },
  modes: {
    '1': 'Conferentie — iedereen kan spreken',
    '2': 'Webinar — één iemand spreekt, de anderen luisteren',
  },
  placements: {
    '1': 'Rasterweergave',
    '2': 'Mini-ik',
    '3': 'Schijnwerpers',
  },
  perm: {
    head: 'Browsermachtingen toestaan',
    video: 'Video',
    audio: 'Audio',
    notif: 'Notificaties',
  },
  videoMenu: {
    hint: 'Context menu',
    expand: 'Uitbreiden',
    pip: 'Hou bovenaan',
    fullscreen: 'Volledig scherm',
    fullscreenOff: 'Verlaat volledig scherm',
    volume: 'Volume',
    restore: 'Herstel',
    kick: 'Verwijder deelnemer',
    mute: 'Demp (enkel voor jou)',
    unmute: 'Dempen opheffen',
    pm: 'Privé chat',
    makeHost: 'Beheerder rol doorgeven',
  },
  controls: {
    sharing: 'Delen',
    cam: 'Camera',
    mic: 'Microfoon',
    chat: 'Chat',
    exit: 'Verlaten',
    destroy: 'Meeting beëindigen',
    settings: 'Instellingen',
    plugin: 'Plugins',
    dots: 'Context menu',
    invite: 'Uitnodigen',
    ss: 'Deel scherm',
    stopSharing: 'Stop delen',
    board: 'Whiteboard',
    hand: 'Steek je hand op',
    lock: 'Vergrendelen',
    layouts: 'Plaatsing',
    emoji: 'Emojis',
    attach: 'Voeg bestand toe',
    setLock: 'Vergrendel de ruimte',
    resetLock: 'Ontgrendel de ruimte',
    setPwd: 'Stel een wachtwoord in',
    rotate: 'Achter/Voor camera',
    more: 'Meer',
    users: 'Deelnemers',
  },
  reactions: {
    handRaised: 'Gebruiker %s wil graag spreken 🎤',
  },
  video: {
    you: 'Jij (klik om naam te geven)',
    sharing: 'Je deelt je scherm',
  },
  settings: {
    tabs: {
      audio: 'Audio',
      video: 'Video',
      general: 'Algemeen',
      help: 'Hulp',
      chat: 'Chat',
      peers: 'Deelnemers',
      lobby: 'Wachtruimte',
    },
    audioQ: 'Max samplefrequentie',
    videoQ: 'Max video kwaliteit',
    screenQ: 'Max scherm delen kwaliteit',
    bandwidthQ: 'Bandbreedte profiel',
    soundEffects: 'Geluid effecten',
    audioDevices: 'Audio bronnen',
    videoDevices: 'Video bronnen',
    language: 'Taal',
    theme: 'Kleurenthema',
    requestAudio: 'Audiotoestemming vragen',
    requestVideo: 'Videotoestemming vragen',
    testOutput: 'Audio-uitgang testen',
    flipFace: 'Spiegel je cameravoorbeeld',
    requireName: 'Naam nodig',
    debug: 'Debug modus',
    noPreview: 'Chats starten zonder voorbeeld',
    menuPos: 'Menu plaatsing',
    menuPosO: {
      '1': 'top',
      '2': 'bodem',
    },
    name: 'Je weergavenaam instellen/wijzigen',
    phName: 'je naam',
  },
  home: {
    title: 'Je persoonlijke vergaderruimte',
    btnGo: 'Start!',
    nameRoom: 'meeting naam:',
    placeholder: 'typ hier',
    rejoinRoom: 'of opnieuw deelnemen aan',
    poweredBy: 'Aangedreven door <a href="https://xroom.app">xroom.app</a>',
    roomHint: 'Voer ruimtenaam in aub',
  },
  pre: {
    selectMode: 'Kies meeting type',
    selectedMode: 'Meeting type',
    btnGo: 'Instappen',
    btnPreview: 'Voorbeeld',
    avaPicker: 'Kies avatar (toont als de video is uitgeschakeld)',
    sizeLimitReached: 'Deze ruimte is beperkt in grootte en de limiet is bereikt',
    roomBooked: 'Er vindt binnenkort een evenement plaats in deze ruimte: <span>%s</span>.<br/>Gelieve te wachten tot de vergadering begint.',
    roomInfo: 'Ruimte info',
    phInfo: 'Voer ruimte info in',
    pendingAdmission: 'Gelieve te wachten tot de gastheren je binnenlaten.',
    p2pMode: 'Peer-to-peer modus',
    btnGoHome: 'Ga naar startpagina',
    btnAsHost: 'Binnengaan als beheerder',
    roomLocked: 'Deze ruimte is vergrendeld door de beheerder.<br />Gelieve aan te kloppen om binnen te gaan.',
    roomLockedInfo: 'Gelieve je naam in te voeren.<br />Anders staat de beheerder je mogelijk niet toe tot de vergadering.',
  },
  inviter: {
    info: 'Deel onderstaande link om anderen uit te nodigen voor de vergadering.',
    head: 'Ruimte link:',
    btnCopy: 'Kopieer link',
    btnShare: 'Deel link',
    ntfCopied: 'De link werd gekopieerd!',
  },
  chat: {
    publicChat: 'Publieke chat',
    chatWith: 'Chat met %s',
    fileSending: 'Bestand versturen: ',
    fileReceived: 'Bestand ontvangen: ',
    phInput: 'Schrijf een bericht...',
    me: 'ik',
    dropMe: 'Laat hier vallen!',
    atTime: 'om %s',
    recvProgress: 'Versleutelde gegevens ontvangen: %s%...',
  },
  peers: {
    muteOnEntry: 'Deelnemers dempen bij binnenkomst',
    camsOff: 'Alle camera\'s uitschakelen',
    micsOff: 'Alle deelnemers dempen',
  },
  knockers: {
    phEmpty: 'Als iemand aanklopt om je ruimte binnen te komen, zullen ze hier verschijnen, wachtend op je goedkeuring.',
  },
  webinar: {
    peersCount: {
      one: '%s persoon is aan het kijken',
      many: '%s personen zijn aan het kijken',
    },
  },
  plugins: {
    by: 'door',
    size: 'Grootte: %s kB',
    phSearch: 'zoeken...',
    source: 'Broncode: ',
    apiDocs: 'API docs',
    vendor: 'Verkoper:',
    btnAdd: 'Voeg eigen toe',
    add: {
      title: 'Voeg nieuwe plugin toe',
      descr: '⚙️ Een nieuwe plugin aan het ontwikkelen? Voeg het hier toe om te testen. Het wordt enkel in je eigen browser opgeslagen.',
      name: 'Wat is de plugin naam?',
      rootUrl: 'Waar is de plugin gelokaliseerd?',
      loaded: 'Succes! Het is geladen!',
      loadFailed: 'Kon plugin niet laden.',
    }
  },
  help: {
    sevenTips: 'Top 7 Problemen/Oplossingen',
    connIssues: 'Connectieproblemen',
    laggyMedia: 'Trage audio/video',
    unlockMedia: 'Deblokkeer camera/microfoon',
    faq: 'Ga naar FAQ',
    submitFeature: 'Vraag een nieuwe functie aan',
  },
}
