export default {
  self: 'xroom',
  on: 'Ligado',
  off: 'Desligado',
  title: 'Precisa de uma sala de conferência?',
  buttons: {
    ok: 'OK',
    yes: 'Sim',
    no: 'Não',
    cancel: 'Cancelar',
    retry: 'De novo',
    chooseWindow: 'Escolher janela',
    wholeScreen: 'Tela inteira',
    install: 'Adicionar',
    uninstall: 'Remover',
    send: 'Enviar',
    close: 'Fechar',
    hide: 'Esconder',
    knock: 'Toc-Toc',
    allowIn: 'Permitir entrar',
    deny: 'Negar',
    enterAnyway: 'Entrar de qualquer forma',
    details: 'Detalhes',
  },
  mbox: {
    notSupported: 'Parece que este navegador não suporta XROOM ou o WebRTC está desativado. 😢',
    success: 'Operação bem sucedida',
    failure: 'Operação falhou',
    enterRoomName: 'Digite o nome da sala',
    isCamOn: 'A câmera está ligada?',
    isCamOnText: 'Verifique, por favor, se não bloqueou acidentalmente a câmera e aperte "Repetir".',
    isMicOn: 'Microfone está ligado?',
    isMicOnText: 'Se deseja conversar, de permissão ao microfone. Apos dar permissão, aperte em "Repetir".',
    iWillOnlyWatch: 'Apenas irei assistir',
    iWillOnlyListen: 'Apenas irei ouvir',
    screenSharingText: 'Compartilhamento de tela não permitido. Certifique-se de que não está bloqueado para esta página.<br><br>Além disso, esse recurso só é compatível com navegadores modernos, como Chrome ou Firefox.',
    cannotFile: 'Como não recebemos seu arquivo, não conseguimos enviá-lo após diversas tentativas. Precisa ser feito onde tem participantes.',
    cannotMessage: 'Como não recebemos sua mensagem, não conseguimos enviá-la após diversas tentativas. Precisa ser feito onde tem participantes.',
    roomLockedText: 'Sala trancada',
    oops: 'Desculpe',
    kickedOutText: 'Você foi expulso',
    areYouSure: 'Tem certeza?',
    restartRequiredText: 'Esta alteração afeta muitos participantes, reinicialização necessária, não se preocupe, será rápido!',
    onlySafariOnIOS: 'Em iOS apenas Safari é compativel.',
    cannotLoadPlugin: 'Plugin "%s" não é compativel com o browser',
    confirmFileSend: 'Deseja enviar?',
    whatIsYourName: 'Digite seu nome',
    setVideoVolume: 'Definir volume para este vídeo',
    roomLockedTryKnockText: 'Sala bloqueada no momento. Peça permissão para entrar.',
    knockingFailedText: 'Tentativa falhou',
    doYouWantToKick: 'Quer expulsar este participante?',
    deviceChanged: 'Adicionou/Removeu novo dispositivo. Se não estiver funcionando, escolha manualmente a partir das definições.',
    allowCameraPlz: 'Após clicar em OK <b>pertmitirá o</b> xroom utilizar sua camera.<br><br>Não se preocupe! Poderá desligar novamente antes de entrar em uma sala a partir do menu inferior se quer permanecer invisivel.',
    tooOldBrowser: 'Navegador muito antigo ou incompatível. Muitas funcionalidades podem não estar disponiveis.',
    pluginsLoadFailed: 'Falha ao carregar plugin',
    protoExpired: 'Versão muito antiga. Aperte por favor Ctrl&nbsp;+&nbsp;Shift&nbsp;+&nbsp;F5 para recarregar. Se voltar a ver esta imagem, por favor limpe o chache.',
    peerError: 'Ocorreu um erro ao trocar informações com o ponto de acesso. Sugerimos que recarregue a página.',
    enterpriseOnly: 'Funcionalidades apenas para empresas.',
    pluginSuggested: 'Utilizador %s sugeriu para instalar o plugin %s. Proceder?',
    hostRoleRequired: 'Funcionalidades de anfitrião necessária para esta operação.',
    alreadyHosted: 'Sala virtual com este nome já em uso. Não crie salas identicas em navegadores diferentes. 😉',
    roomLockedPassword: 'Sala protegida com senha. Inserir a senha para ter acesso.',
    roomDestroyed: 'Sala foi removida. Será redirecionado para a página inicial.',
    roomBooked: 'Sala virtual agendada, não poderá ser criada até que agendamento expire ou seja removida.',
    nameRequired: 'O anfitrião da sala exige que você defina seu nome primeiro.',
    pipNotSupported: 'Your browser supports "picture-in-picture" mode but it is disabled somewhere in its settings.',
    copyFailed: 'Copying failed. This may be a result of your device restrictions.',
    noCryptoWarning: 'This browser does not support cryptography. It is not safe to continue.',
    bigFileDecryptWarn: 'Downloading has started. It may take a few seconds to decrypt the file.',
  },
  notify: {
    slowPlugins: 'Os plugins levam muito tempo para carregar. Considere remover o mais pesado.',
  },
  home: {
    nisdos: 'Não utilizamos cockies',
    title: 'Your personal conference room',
    btnGo: 'Criar!',
    knowMore: 'Sobre xroom',
    nameRoom: 'nome da sala:',
    placeholder: 'escreva aqui',
    rejoinRoom: 'ou juntar-se novamente',
  },
  wl: {
    poweredBy: 'Desenvolvido por ',
  },
  modes: {
    1: 'Conferência',
    2: 'Webinar',
  },
  pre: {
    selectMode: 'Escolha o tipo de sala',
    checkIt: 'Verifique sua câmera e seu microfone',
    btnGo: 'Entrar',
    knockDenied: 'Seu pedido para entrar foi negado. Não pode entrar na sala. :(',
    knockRequested: 'Aguardando permissão. 👀',
    noAudio: '⚠️ Nenhum sinal de microfone detectado',
    roomIsBusyWebinar: 'O webinar/stream está em curso (%s / %s)',
    roomIsBusyConference: 'A conferência está em curso (%s / %s)',
    sizeLimitReached: 'Sala virtual limitada para uma quanidade de participantes que ja foi atingida',
    roomBooked: 'There is going to be an event in this room at <b>%s</b>, but it has not started yet.',
  },
  videoMenu: {
    hint: 'Alterar menu',
    expand: 'Expandir',
    pip: 'Keep on top',
    fullscreen: 'Tela inteira',
    volume: 'Volume ±',
    restore: 'Restaurar',
    kick: 'Expulsar',
    mute: 'Mudo',
  },
  controls: {
    ss: 'Compartilhamento de Tela %s',
    cam: 'Cam %s',
    mic: 'Mic %s',
    chat: 'Chat %s',
    exit: 'Sair',
    destroy: 'Destruir',
    xroom: 'Desenvolvido por xroom',
    settings: 'Definições',
    plugins: 'Plugins',
    media: 'Media',
    more: 'Mais',
    letMeSpeak: 'Deixe-me falar',
    lock: 'Locking',
  },
  lockStatus: {
    locked: 'Room is locked',
    open: 'Room is open',
    protected: 'Room is password-protected',
    placeholder: 'room password',
  },
  reactions: {
    letMeSpeak: 'Quero falar!',
  },
  waiting: {
    invite: 'Convide seus colegas',
    beforeCopy: 'click para copiar',
    afterCopy: 'Copiado. Agora partilhe!',
    webinar: 'Webinar não foi iniciado',
  },
  video: {
    you: 'Voce (click para editar nome)',
    someone: 'Alguem',
    knocking: 'está a bater...',
    poorNet: 'Conexão probre',
  },
  chat: {
    fileSending: 'Enviando arquivo: ',
    fileReceived: 'Arquivo recebido: ',
    inputPlaceholder: 'escreva sua mensagem e aperte "enter" ...',
    me: 'eu',
    dropMe: 'Largar!',
  },
  webinar: {
    peersCount: '%s pessoas assistindo',
  },
  settings: {
    experimental: '*) experimental, works unstably',
    showCameraWithScreen: 'Mostrar câmera durante a o compartilhamento de tela (BETA)',
    audioQ: 'Audio quality',
    videoQ: 'Video quality',
    screenQ: 'Screen sharing quality',
    bandwidthQ: 'Bandwidth profile',
    autoGetIn: 'Iniciar chat sem previsualização',
    soundEffects: 'Efeitos sonoros',
    noisyBackground: 'Estou em um local com barulho',
    rtcDebug: 'Debug RTC',
    audioDevices: 'Recursos de áudio',
    videoDevices: 'Recursos de vídeo',
    language: 'Idioma',
    theme: 'Cor do tema',
    server: 'Servidor',
    keepControls: 'Manter controles visíveis',
  },
  plugins: {
    by: 'por',
    size: 'Tamanho: %s kB',
    searchPlaceholder: 'procurar...',
    source: 'Código fonte:',
    apiDocs: 'API docs',
    vendor: 'Vendor:',
    add: {
      title: 'Adicionar novo plugin',
      descr: '⚙️ A desenvolver novo plugin? Adicione aqui para testar. Não foi salvo, Ao recarregar a página removerá da memória.',
      name: 'Qual nome do plugin?',
      rootUrl: 'Qual o root do plugin?',
      loaded: 'Sim! Foi descarregado!',
      loadFailed: 'Falhou descarregamento do plugin',
    }
  },
  tips: {
    prefix: 'Dica do dia: ',
    lines: [
      'Mudo activa/desactiva com frequência? Existe um atalho "m" para tal.',
      'Duplo click no vídeo remoto para ecrã inteiro.',
      'Precisa bloquear a sala? Adicione esta funcionalidade em "plugins".',
      'Usa Slack e gostaria de economizar tempo? Experimente o nosso <a href="//xroom.app/en/library/slack-bot" target="_blank">Slack bot</a>.',
      'Perdeu videochamada no telegram? Nosso <a href="//xroom.app/en/library/telegram-bot" target="_blank">BOT Telegram</a> está para ajudar.',
      'Precisa partilhar a imagem copiada? Aperte Ctrl+V no chat, nós tratamos do recto.',
      'Click no seu nome para alterar localmente e para os participantes.',
      'Alguma vez necessitou de partilhar o ecrã com simples click? Experimente nosso gravador de ecrã em "plugins".',
      'Precisa de rascunho durante a videoconferencia? Experimente em "plugns. Não se esqueça de partilhar o ecrã.',
      'Click em seu nome ou "Você" para alterar o nome.',
      'Click no nome do participante para ajustar o volume.',
    ]
  },
}
