export default {
  self: 'xroom',
  on: 'on',
  off: 'off',
  title: 'Vrei o camera de videoconferinta gratuit?',
  buttons: {
    ok: 'OK',
    yes: 'Da',
    no: 'Nu',
    cancel: 'Renunt',
    retry: 'Reincerc',
    chooseWindow: 'Alege o fereastra',
    wholeScreen: 'Tot ecranul',
    install: 'Adauga',
    uninstall: 'Sterge',
    send: 'Trimite',
    close: 'Inchide',
    hide: 'Ascunde',
    knock: 'Knock-knock',
    allowIn: 'Permite',
    deny: 'Interzice',
    enterAnyway: 'Enter anyway',
  },
  mbox: {
    notSupported: 'Se pare ca browser-ul tau nu suporta sau WebRTC este nefunctional. 😢',
    success: 'Actiune cu succes',
    failure: 'Actiune esuata',
    enterRoomName: 'Scrie numele camerei de videoconferinta',
    isCamOn: 'Este camera video pornita?',
    isCamOnText: 'Verifica daca nu ai blocat accidental camera sau microfonul pentru acest site si apasa "Reincearca".',
    isMicOn: 'Este pornit microfonul?',
    isMicOnText: 'Daca doresti sa poti vorbi aici trebuie sa permiti accesul la microfon. Permite asta si apoi apasa "Reincearca".',
    iWillOnlyWatch: 'Doresc doar sa ma uit',
    iWillOnlyListen: 'Doresc doar sa ascult',
    screenSharingText: '"Screen sharing" nu este permis. Verifica daca nu cumva acest lucru este blocat pentru aceasta pagina',
    cannotFile: 'Since we don\'t even touch your files we cannot deliver them after someone connects. You need to do it when people are in.',
    cannotMessage: 'Since we don\'t even touch your messages we cannot deliver them after someone connects. You need to do it when people are in.',
    roomLockedText: 'Aceasta camera de videoconferinte are acces blocat pentru altii',
    oops: 'Imi pare rau',
    kickedOutText: 'Ai fost dat afara',
    areYouSure: 'Esti sigur?',
    restartRequiredText: 'Aceasta setare necesita repornirea. Va fi rapid, nu te ingrijora!',
    onlySafariOnIOS: 'Pentru iOS doar Safari este suportat',
    cannotLoadPlugin: 'Plugin "%s" nu suporta browser-ul tau',
    confirmFileSend: 'Vrei sa trimiti asta?',
    whatIsYourName: 'Scrie numele tau',
    setVideoVolume: 'Seteaza nivelul sunetului la acest video',
    roomLockedTryKnockText: 'Camera de videoconferinta este incuiata. Pentru a cere permisunea sa intri apasa pe "Knock-knock".',
    knockingFailedText: 'Knocking attempt failed',
    doYouWantToKick: 'Vrei sa dai afara acest utilizator?',
    deviceChanged: 'Tocmai ce ai schimbat un nou device. Daca nu functioneaza corect, du-te la Settings',
    allowCameraPlz: 'Dupa ce apesi pe OK <b>permite</b> aplicatiei sa foloseasca camera video.<br><br> Apoi, poti oricand sa o opresti sau sa o repornesti',
    tooOldBrowser: 'Browser-ul tau este prea vechi sau este tip Microsoft. Multe functionalitati nu vor functiona ok.',
    pluginsLoadFailed: 'Plugin-ul nu a putut fi incarcat',
    protoExpired: 'Client web prea vechi. Apasa Ctrl&nbsp;+&nbsp;Shift&nbsp;+&nbsp;F5 pentru reincarcare. Daca vezi iar acest mesaj curata manual cache-ul browser-ului.',
    peerError: 'Ceva nu a mers bine. Reincarca pagina.',
    enterpriseOnly: 'Aceasta functionalitate nu este permisa decat detinatorului aplicatiei.',
    pluginSuggested: 'Utilizatorul %s doreste sa instaleze plugin-ul %s. Ii permiti?',
    hostRoleRequired: 'Pentru aceasta actiune trebuie sa fii HOST.',
    alreadyHosted: 'Esti deja in aceasta camera de videoconferinta. Nu poti fi in ea in acelasi timp, in 2 tab-uri de browser. 😉',
    roomLockedPassword: 'Accesul la camera de videoconferinta necesita paraola. Pentru a intra, scrie parola.',
    roomDestroyed: 'Aceasta camera de videoconferinte nu mai exista.',
    roomBooked: 'Camera de videoconferinta este blocata si nu mai poate fi creata pana la expirarea ei.'
  },
  notify: {
    slowPlugins: 'Plugin-ul nu poate fi incarcat.',
  },
  home: {
    nisdos: 'Nu se foloseste cookies',
    title: 'Camera ta de videoconferinte',
    btnGo: 'Hai!',
    knowMore: 'Despre aplicatie',
    nameRoom: 'Numele camerei de videoconferinta:',
    placeholder: 'scrie aici',
    rejoinRoom: 'sau reconecteaza-te',
  },
  wl: {
    poweredBy: 'Powered by ',
  },
  modes: {
    1: 'Videoconferinta',
    2: 'Webinar',
  },
  pre: {
    selectMode: 'Alege tipul',
    checkIt: 'Verifica microfonul',
    btnGo: 'Intra',
    knockDenied: 'Acces interzis. Inca nu poti intra. :(',
    knockRequested: 'Asteapta permisiunea de intrare. 👀',
    noAudio: '⚠️ Nu a fost detectat semnal audio',
    roomIsBusyWebinar: 'Webinarul este pornit (%s × 🙂)',
    roomIsBusyConference: 'Videoconferinta este pornita (%s × 🙂)',
    sizeLimitReached: 'Limita de locuri a fost depasita',
  },
  videoMenu: {
    hint: 'Toggle menu',
    expand: 'Expand',
    fullscreen: 'Full screen',
    volume: 'Volume ±',
    restore: 'Restore',
    kick: 'Kick',
    mute: 'Fara sonor',
  },
  controls: {
    ss: 'Screen sharing %s',
    cam: 'Cam %s',
    mic: 'Mic %s',
    chat: 'Chat %s',
    exit: 'Exit',
    destroy: 'Destroy',
    xroom: 'Powered by RoboMarketing',
    settings: 'Setari',
    plugins: 'Plugin',
    media: 'Media',
    more: 'Mai mult',
    letMeSpeak: 'Vreau sa vorbesc!',
  },
  reactions: {
    letMeSpeak: 'Vreau sa vorbesc!',
  },
  waiting: {
    invite: 'Invita participanti',
    beforeCopy: 'click pentru copiere',
    afterCopy: 'Copita. Acum distribuie!',
    webinar: 'Webinar-ul inca nu a pornit',
  },
  video: {
    you: 'You (click pe nume)',
    someone: 'Cineva',
    knocking: 'doreste sa intre...',
    poorNet: 'conexiune slaba',
  },
  chat: {
    fileSending: 'Trimitere fisier: ',
    fileReceived: 'Fisier primit: ',
    inputPlaceholder: 'scrie mesajul si trimite ...',
    me: 'eu',
    dropMe: 'Drop me!',
  },
  webinar: {
    peersCount: '%s participanti se uita',
  },
  settings: {
    experimental: '*) experimental, works unstably',
    showCameraWithScreen: 'Arata camera video in timp ce fac sharescreen*',
    qualityLevel: 'Calitate maxima (necesita resurse mai mari)',
    autoGetIn: 'Porneste chats fara preview',
    soundEffects: 'Efecte sonore',
    noisyBackground: 'Sunt in spatiu zgomotos',
    rtcDebug: 'Debug RTC',
    audioDevices: 'Surse audio',
    videoDevices: 'Surse video',
    language: 'Limba
    theme: 'Color theme',
    server: 'Server',
  },
  plugins: {
    by: 'de',
    size: 'marime: %s kB',
    searchPlaceholder: 'cautare...',
    source: 'Cod sursa',
    add: {
      title: 'Adauga un plugin',
      descr: '⚙️ Developing a new plugin? Add it here to test. It is not saved, reloading the page removes it from memory. Plugins API manual is available <a href="https://github.com/punarinta/xroom-plugins" target="_blank">here</a>.',
      name: 'What\'s the plugin name?',
      rootUrl: 'Where is the plugin root?',
      loaded: 'Yaay! It\'s loaded!',
      loadFailed: 'Failed loading plugin',
    }
  },
  feedback: {
    header: 'Oh, imi pare rau, asteapta un pic...',
    question: 'Acum este mai bine?',
    videoFroze: 'Nu merge video',
    soundLagged: 'Nu, sunetul este intarziat',
    cantConnect: 'Nu, cineva nu a putut sa se conecteze',
    smthElse: 'Altceva:',
    feedbackInput: 'lasa un feedback...',
    contactMe: 'Contacteaza-ma:',
    emailInput: 'adresa ta de e-amil...',
  },
  tips: {
    prefix: 'Tip of the day: ',
    lines: [
      'Mute/unmute often? There\'s a hot key "m" for that.',
      'Double click a remote video to make it full screen.',
      'Need to lock your room? Just add the room locking in plugins below.',
      'Use Slack and want to save more time? Try out our <a href="//about.xroom.app/en/library/slack-bot" target="_blank">Slack bot</a>.',
      'Miss video calls in Telegram? Our <a href="//about.xroom.app/en/library/telegram-bot" target="_blank">Telegram bot</a> is there to help.',
      'Need to share a copied image? Ctrl+V in the chat, we\'ll cover the rest.',
      'Click your name to change it both locally and for your peers.',
      'Ever needed to record your screen with just a few clicks? Try our screen recording plugin.',
      'Need to sketch during a call — try out the sketching plugin. Don\'t forget to turn on screen sharing.',
      'Click your name or "You" to rename yourself for everyone.',
    ]
  },
}
