export default {
  self: 'xroom',
  on: 'på',
  off: 'av',
  title: 'Behövs ett konfrum?',
  buttons: {
    ok: 'OK',
    yes: 'Ja',
    no: 'Nej',
    cancel: 'Avbryt',
    retry: 'Igen',
    chooseWindow: 'Välj ett fönster',
    wholeScreen: 'Hela skärmen',
    install: 'Lägg till',
    uninstall: 'Ta bort',
    send: 'Skicka',
    close: 'Stäng',
    hide: 'Dölj',
    knock: 'Knack knack',
    allowIn: 'Låt in',
    deny: 'Neka',
  },
  mbox: {
    notSupported: 'Det känns som denna webläsare stöder inte XROOM eller WebRTC är inaktiverat. 😢',
    success: 'Åtgärden lyckades',
    failure: 'Åtgärden misslyckades',
    enterRoomName: 'Vänligen ange rumsnamnet',
    isCamOn: 'Är kameran på?',
    isCamOnText: 'Kontrollera att du inte har oavsiktligt blockerat din kamera / mikrofon på den här sidan och sedan tryck på "Igen".',
    isMicOn: 'Är mikrofonen på?',
    isMicOnText: 'Om du vill prata behöver vi ha tillgång till din mikrofon. Avblockera den på och denna sida och sedan tryck på "Igen".',
    iWillOnlyWatch: 'Jag ska bara titta',
    iWillOnlyListen: 'Jag ska bara lyssna',
    screenSharingText: 'Skärmdelning är inte tillåtet. Se till att det inte är blockerat för den här sidan.<br><br>Viktigt: funktionen stöds endast av moderna webbläsare som Chrome eller Firefox.',
    cannotFile: 'Eftersom vi inte ens berör dina filer kan vi inte leverera dem till någon efter en anslutar. Du behöver göra det online.',
    cannotMessage: 'Eftersom vi inte ens berör dina meddelanden kan vi inte leverera dem till någon efter en anslutar. Du behöver göra det online.',
    roomLockedText: 'Det här rummet är tyvärr låst.',
    oops: 'Oops',
    kickedOutText: 'Du har sparkats ut från det här rummet.',
    areYouSure: 'Är du säker?',
    doYouWantToLeave: 'Vill du verkligen lämna streamet?',
    doYouWantToLeaveAsHost: 'Vill du verkligen sluta streama?',
    restartRequiredText: 'Denna inställning påverkar så mycket att omstartet behövs. Det blir snabbt, vi lovar!',
    onlySafariOnIOS: 'På iOS stöds endast Safari.',
    cannotLoadPlugin: 'Plugin "%s" stöds inte i din webbläsare',
    confirmFileSend: 'Vill du skicka detta?',
    whatIsYourName: 'Ange ett nytt namn',
    setVideoVolume: 'Ställ in ljudnivån',
    roomLockedTryKnockText: 'Rummet är låst. Du kan be om att gå in genom att "knacka".',
    knockingFailedText: 'Knackningsförsöket misslyckades',
    doYouWantToKick: 'Vill du sparka ut den här användaren?',
    deviceChanged: 'Du har anslutit eller tagit bort en input-enhet. Om det inte fungerar nu välj det gärna manuellt på inställningar.',
    allowCameraPlz: 'Efter du trycker på OK, <b>låt</b> xroom använda din kamera.<br><br>Oroa dig inte, du ska kunna stänga av det igen innan du går in i rummet från menyn längst ner om du vill stanna osynlig.',
    tooOldBrowser: 'Din webbläsare är för gammal eller tillverkad av Microsoft. Många funktioner kan saknas.',
    pluginsLoadFailed: 'Det gick inte att ladda plugin',
    researchConsent: 'Hi!<br><br>We are currently doing a serious upgrade to improve the service.<br><br>If you face any error you are very welcome to report it to hello@xroom.app',
    protoExpired: 'För gammal klientversion. Tryck på Ctrl&nbsp;+&nbsp;F5 för att ladda om. Om du ser detta meddelande igen, rensa webbläsarens cache manuellt tack.',
    peerError: 'Något gick fel när du utbytte data med andra. Vi föreslår att du laddar om sidan.',
    enterpriseOnly: 'This is an enterprise only feature.',
    pluginSuggested: 'Användare %s föreslog att du installerar plugin %s. Vill du göra det?',
    hostRoleRequired: 'Host-roll krävs för den här åtgärden.',
  },
  home: {
    nisdos: 'Inga "cookies" används här',
    title: 'Ditt eget konferensrum',
    btnGo: 'Kör!',
    knowMore: 'Om xroom',
    nameRoom: 'namnge rummet:',
    placeholder: 'skriv här',
    rejoinRoom: 'eller återvända till',
  },
  wl: {
    poweredBy: 'Drivs av ',
  },
  pre: {
    checkIt: 'Ser du bra ut?',
    btnGo: 'Börja',
    knockDenied: 'Din knock-begäran har nekats. Du kan inte komma in i rummet. :(',
    knockRequested: 'Vänta på tillstånd. Andra kan se dig genom en kikhull. 👀',
    noAudio: '⚠️ Vi känner inte din mikrofon',
    roomIsBusyWebinar: 'En webinar/stream är redan på gång (%s × 🙂)',
    roomIsBusyConference: 'Ett samtal är redan på gång (%s × 🙂)',
    startWebinar: 'Starta som en stream/webinar',
  },
  videoMenu: {
    hint: 'Meny',
    expand: 'Förstora',
    fullscreen: 'Fullskärm',
    volume: 'Ljudnivå ±',
    restore: 'Återställa',
    kick: 'Kicka',
  },
  controls: {
    ss: 'Skärmdeln. %s',
    cam: 'Kam %s',
    mic: 'Mik %s',
    chat: 'Chatt %s',
    exit: 'Avsluta',
    xroom: 'Drivs av xroom',
    settings: 'Inställn.',
    plugins: 'Plug-in',
    media: 'Media',
    more: 'Mer',
    letMeSpeak: 'Jag vill prata',
  },
  reactions: {
    letMeSpeak: 'Jag vill prata!',
  },
  waiting: {
    invite: 'Bjud in dina kollegor',
    beforeCopy: 'klicka för att kopiera',
    afterCopy: 'Kopierats. Dela nu!',
    webinar: 'Webinar har inte startat',
  },
  video: {
    you: 'Du (klicka för att namnge)',
    someone: 'Någon',
    knocking: 'knackar...',
    poorNet: 'dålig anslutning',
  },
  chat: {
    fileSending: 'Skickar en fil: ',
    fileReceived: 'En fil har tagits emot: ',
    inputPlaceholder: 'skriv ett meddelande ...',
    me: 'jag',
    dropMe: 'Släpp mig!',
  },
  webinar: {
    peersCount: '%s personer tittar',
  },
  settings: {
    experimental: '*) experimentellt, fungerar ostabilt',
    showCameraWithScreen: 'Använd kameran under skärmdelning *',
    qualityLevel: 'Hög kvalitet (bra bandbredd behövs)',
    autoGetIn: 'Starta chattar utan granskning',
    soundEffects: 'Ljudeffekter',
    noisyBackground: 'Jag på en högljudd plats',
    rtcDebug: 'Felsök RTC',
    audioDevices: 'Audio källor',
    videoDevices: 'Video källor',
    language: 'Språk',
    theme: 'Färgtema',
    server: 'Server',
  },
  plugins: {
    by: 'av',
    size: '%s kB',
    searchPlaceholder: 'söka...',
    source: 'Källkod',
    add: {
      title: 'Lägg till ett nytt plugin',
      descr: '⚙️ Utvecklar du ett nytt plugin? Lägg till det här för att testa. Det sparas inte, om du laddar om sidan tas det bort från minnet. Plugin API handbok är tillgänglig <a href="https://github.com/punarinta/xroom-plugins" target="_blank">här</a>.',
      name: 'Vad heter plugin?',
      rootUrl: 'Var är URL-adressen för plugin?',
      loaded: 'Yaay! Det är laddat!',
      loadFailed: 'Det gick inte att ladda plugin',
    }
  },
  feedback: {
    header: 'Åh, en sekund bara...',
    question: 'Gick allting bra denna gång?',
    videoFroze: 'Nej, video frös',
    soundLagged: 'Nej, ljudet var försenat',
    cantConnect: 'Nej, någon kunde inte ansluta',
    smthElse: 'Något annat:',
    feedbackInput: 'lämna ditt feedback...',
    contactMe: 'Vänligen kontakta mig:',
    emailInput: 'mitt email...',
  },
  tips: {
    prefix: 'Dagens tips: ',
    lines: [
      'Mute/unmute often? There`s a hot key "m" for that.',
      'Double click the remote video to make it full screen.',
      'Need to lock your room? Just add the room locking in plugins below.',
      'Use Slack and want to save more time? Try out our <a href="//about.xroom.app/en/library/slack-bot" target="_blank">Slack bot</a>.',
      'Miss video calls in Telegram? Our <a href="//about.xroom.app/en/library/telegram-bot" target="_blank">Telegram bot</a> is there to help.',
      'Need to share a copied image? Ctrl+V in the chat, we`ll cover the rest.',
      'Lock your room in one click, use locking plugin',
      'Click your name to change it both locally and for your peers.',
      'Ever needed to record your screen with just a few clicks? Try our screen recording plugin.',
    ]
  },
}
