export default {
  self: 'xroom',
  on: '开',
  off: '关',
  title: '需要一间会议室吗？',
  buttons: {
    ok: 'OK',
    yes: '是',
    no: '否',
    cancel: '取消',
    retry: '重试',
    chooseWindow: '请选择视窗',
    wholeScreen: '全屏',
    install: '增加',
    uninstall: '撤除',
    send: '发送',
    close: '关闭',
    hide: '隐藏',
    knock: '敲敲',
    allowIn: '允许',
    deny: '拒绝',
  },
  mbox: {
    notSupported: '该浏览器似乎不支持XROOM或WebRTC已禁用。😢',
    success: '操作成功',
    failure: '操作失败',
    enterRoomName: '请输入名称',
    isCamOn: '相机是否有开?',
    isCamOnText: '请检查您是否没有意外地阻止此站点上的相机/麦克风，然后按“重试”。',
    isMicOn: '麦克风是否有开？',
    isMicOnText: '如果您打算讲话，我们需要您的麦克风许可。在此页面上允许它，然后按“重试”。',
    iWillOnlyWatch: '我只会看',
    iWillOnlyListen: '我只会听',
    screenSharingText: '不允许屏幕共享。请确保此页面未被阻止。<br><br>此功能仅受现代浏览器（例如Chrome或Firefox）支持。',
    cannotFile: '由于我们不会触碰您的文件，因此我们无法在有人连接后将其交付。您需要在线进行。',
    cannotMessage: '由于我们不会触碰您的讯息，因此我们无法在有人连接后将其交付。您需要在线进行。',
    roomLockedText: '此房间已上锁',
    oops: '抱歉',
    kickedOutText: '您已被踢出',
    areYouSure: '是否确定？',
    doYouWantToLeave: '是否要离开？',
    restartRequiredText: '此设置影响了很多东西，因此需要重新加载。很快，不用担心！',
    onlySafariOnIOS: '在iOS上，仅支持Safari。 “谢谢你，苹果！',
    cannotLoadPlugin: '插件 "%s" 不支持您的浏览器',
    confirmFileSend: '您确定要发送吗？',
    whatIsYourName: '请输入名字',
    setVideoVolume: '设置此视频的音量',
    roomLockedTryKnockText: '房间目前处于锁定状态。您可以通过“敲门”来寻求进入许可。',
    knockingFailedText: '敲门尝试失败',
    doYouWantToKick: '您要把此用户踢出去吗？',
    deviceChanged: '您已连接/卸下了新的输入设备。如果不起作用，请从“设置”中手动选择。',
    allowCameraPlz: '按“确定”后，请<b>允许</b>xroom使用您的相机。<br><br>别担心！如果您想保持隐身状态，则可以再次关闭它，然后从下方的选项中进入房间。',
    tooOldBrowser: '您的浏览器太旧或由Microsoft生产。许多功能可能无法操作。',
    pluginsLoadFailed: '加载插件失败',
    researchConsent: '嗨！我们正在对p2p网络进行研究。<br><br>您允许我们使用您的流量质量信息进行分析吗？',
  },
  home: {
    nisdos: '我们不使用cookies',
    title: '您的私人会议室',
    btnGo: '继续!',
    knowMore: '关于xroom',
    nameRoom: '命名您的房间：',
    placeholder: '在此输入',
    rejoinRoom: '或重新加入',
  },
  wl: {
    poweredBy: '供应为 ',
  },
  pre: {
    checkIt: '请检查您的麦克风和发型',
    btnGo: '进来',
    knockDenied: '您的敲门请求已被拒绝。您无法进入房间。:(',
    knockRequested: '等待许可。人们可以通过窥视孔看到您。👀',
    noAudio: '⚠️ 未检测到麦克风信号',
  },
  videoMenu: {
    hint: '切换选项',
    expand: '扩大',
    fullscreen: '全屏',
    volume: '音量±',
    restore: '恢复',
    kick: '踢',
  },
  controls: {
    ss: '屏幕共享%s',
    cam: '相机%s',
    mic: '麦克风%s',
    chat: '聊天室%s',
    exit: '出口',
    xroom: '由xroom提供支持',
    settings: '设定值',
    plugins: '外挂程式',
  },
  waiting: {
    invite: '邀请你的同事',
    beforeCopy: '点击复制',
    afterCopy: '复制成功!',
    webinar: '网络研讨会尚未开始',
  },
  video: {
    you: '您',
    someone: '有人',
    knocking: '在敲...',
    poorNet: '连接不良',
  },
  chat: {
    fileSending: '发送文件：',
    fileReceived: '收到的文件：',
    inputPlaceholder: '输入信息，然后按进入...',
    me: '我',
    dropMe: '请给我!',
  },
  webinar: {
    peersCount: '%s人们在看',
  },
  settings: {
    experimental: '*) 实验性，还是不稳定',
    showCameraWithScreen: '在屏幕共享期间显示相机 *',
    qualityLevel: '高质量（使用更多流量）',
    autoGetIn: '在没有预览的情况下开始聊天',
    soundEffects: '声音特效',
    noisyBackground: '我在嘈杂的地方',
    rtcDebug: '调试RTC',
    audioDevices: '音源',
    videoDevices: '视讯来源',
    language: '语言',
  },
  plugins: {
    by: '通过',
    size: '大小：％s kB',
    searchPlaceholder: '搜索中...',
    source: '源代码',
    add: {
      title: '添加新插件',
      descr: '⚙️ 开发新插件？将其添加到此处进行测试。它不会保存，重新加载页面会将其从内存中删除。可以在<a href="https://github.com/punarinta/xroom-plugins" target="_blank">此处</a>获得插件API手册。',
      name: '插件名称是什么？',
      rootUrl: '插件目录在哪里？',
      loaded: '耶！已加载！',
      loadFailed: '加载插件失败',
    }
  },
  feedback: {
    header: '抱歉，请稍等。。',
    question: '这次是否一切顺利？',
    videoFroze: '不，视频冻结',
    soundLagged: '不，声音落后',
    cantConnect: '不，有人无法连接',
    smthElse: '其他：',
    feedbackInput: '请留下您的反馈...',
    contactMe: '请与我联系：',
    emailInput: '你的邮件...',
  },
  tips: {
    prefix: '每日提示：',
    lines:[
      '经常静音/取消静音？有一个热键"m"可使用。',
      '双击远程视频以使其全屏显示。',
      '需要锁定房间吗？只需在下面的插件中添加房间锁定功能即可。',
      '使用Slack并想节省更多时间吗？试用我们的<a href="//about.xroom.app/en/library/slack-bot" target="_blank">Slack机器人</a>。',
      '错过了Telegram中的视频通话吗？我们的<a href="//about.xroom.app/en/library/telegram-bot" target="_blank">Telegram机器人</a>可以为您提供帮助。',
      '需要共享复制的图像吗？在聊天中按Ctrl + V，我们将为您服务。',
      '单击您的名字将可以更改您及您的同伴所显示的名字。',
      '想单击几下便可以记录屏幕吗？试试我们的屏幕录像插件。',
    ]
  },
}
